### DISCUSSION TITLE
Help needed for PowerToy related Window tilling

### DISCUSSION THREAD

**Discussion by k88936** [glzr-io/glazewm#1072] [Q&A] [answered]
1. though I have removed ALL windows rules in my config . PowerToysSettingWindow still cant be moved and resized and tiled
2. Concerning its new function: Command Palatte, I expect it to  be floating(actually it is tiled ,yeah , just the opposite of 1)  , when i boot it,  it will pop up a window, but when i lose its focus, it disappeared ,thus I tried use Process Explorer to git its info and set it to be floating (by its window title or sth) , failed

**Comment by k88936** [comment, marked as answer]
2. solved using autoit:
```yaml

window_rules:
  - commands: ["set-floating"]
    match:
      - window_title: { equals: 'Command Palette' }
```
