### DISCUSSION TITLE
Alt+D Keybinding Cannot Be Disabled - Conflicts with Browser/Application Usage

### DISCUSSION THREAD

**Discussion by litlmike** [glzr-io/glazewm#1119] [Q&A]
## Issue Description
GlazeWM version 3.9.1 appears to have a default Alt+D keybinding that cannot be properly disabled, preventing the standard Alt+D functionality (focus address bar) from working in browsers and other applications.

## Expected Behavior
When Alt+D is not explicitly bound in the user's config file, or when explicitly disabled, the keybinding should pass through to the active application (e.g., Chrome, Firefox, File Explorer) to allow normal Alt+D functionality (focus address/navigation bar).

## Actual Behavior
Alt+D is captured by GlazeWM and appears to trigger workspace switching functionality, even when not explicitly configured in the user's config file. This prevents Alt+D from working in browsers and other applications.

## Environment
- **GlazeWM Version**: 3.9.1
- **Windows Version**: 10.0.19045.5965
- **Installation Method**: winget (no newer versions available)

## Steps to Reproduce
1. Install GlazeWM 3.9.1
2. Use any config file (even without Alt+D bindings)
3. Start GlazeWM
4. Open Chrome/Firefox/File Explorer
5. Press Alt+D
6. **Expected**: Address bar should focus
7. **Actual**: Nothing happens (key is captured by GlazeWM)

## Verification
- When GlazeWM is **stopped**: Alt+D works perfectly in all applications
- When GlazeWM is **running**: Alt+D is captured and doesn't reach applications

## Attempted Solutions
All of the following approaches were tried without success:

### 1. Explicit Ignore Command
```yaml
keybindings:
  - command: "ignore"
    binding: "Alt+D"
```

### 2. Empty Commands Array
```yaml
keybindings:
  - commands: []
    bindings: ["Alt+D"]
```

### 3. Empty Command String
```yaml
keybindings:
  - command: ""
    binding: "Alt+D"
```

### 4. Harmless Override Commands
```yaml
keybindings:
  - command: "nop"
    binding: "Alt+D"
```

```yaml
keybindings:
  - command: "focus workspace current"
    binding: "Alt+D"
```

### 5. Full GlazeWM Restart
- Completely exited GlazeWM (Alt+Shift+E)
- Made config changes
- Restarted GlazeWM
- Issue persisted

## Current User Configuration
The user has a custom config with workspace switching on different keys:
- `Alt+Y` for recent workspace
- `Ctrl+Alt+1-9` for workspace switching
- No explicit Alt+D binding in their config

## Impact
This issue forces users to choose between:
1. Using GlazeWM and losing Alt+D functionality in browsers/applications
2. Not using GlazeWM to preserve standard Alt+D behavior

Alt+D is a very common and important keybinding for web browsing and file navigation, making this a significant usability issue.

## Possible Root Cause
It appears GlazeWM may have a hardcoded default Alt+D binding that cannot be properly overridden or disabled through configuration, even when not explicitly defined in the user's config file.

## Requested Solution
- Allow Alt+D (and other default keybindings) to be completely disabled/removed
- Ensure that disabled keybindings are properly released back to the system
- Consider making fewer keybindings "default" to avoid conflicts with common application shortcuts

## Workaround
Currently, the only workaround is to exit GlazeWM when Alt+D functionality is needed, which defeats the purpose of using a window manager.

Thank you for looking into this issue!
