### DISCUSSION TITLE
Multiple Multi-Monitor Setups

### DISCUSSION THREAD

**Discussion by lyze237** [glzr-io/glazewm#116] [Ideas]
Hey there!

There are some cases where users with laptops have different multi monitor setups (E.g. while they're at their workstation, sharing their screen to meeting room screens, ...)

Therefore, I thought we could change the config a bit to incorporate different rules based on different setups.

Declare an array of monitor setups:
```yaml
setups:
   - name: Laptop
     monitors:
       - id: 1
         resolution: 1920x1080
         dpi: ...

   - name: Workstation
     monitors:
       - id: 1
         resolution: 1920x1080
         dpi: ...
       - id: 2
         resolution: 3840x2160
         dpi: ...

   - name: Meeting Room
     monitors:
       - id: 1
         resolution: 1920x1080
         dpi: ...
       - id: 2
         resolution: 1920x1080
         dpi: ...
```

And then in window rules we could use:
```yaml
workspaces:
    - name: 1
      setups:
         -  name: Laptop
            id:  1
         -  name: Workstation
            id:  1

    - name: 2
      setups:
         -  name: Workstation
            id:  2
```

With that when GlazeWM recognizes the "Laptop" setup it'd bind workspace 1 to the laptops monitor, and when it would recognize the "Workstation" setup it'd bind workspace 1 to the laptops monitor and workstation 2 to the other monitor.

I'm not the best with coming up with something like that but I thought that this would be a good idea to implement, or something similar to this and therefore wanted to ask about opinions!
