### DISCUSSION TITLE
Process vs Title vs Class, exact vs RegEx

### DISCUSSION THREAD

**Discussion by maphew** [glzr-io/glazewm#183] [Q&A]
There are 3 _window_rules_ methods to identify windows to manage:

  match_title
  match_class_name
  match_process_name
  
Does it matter which method is used? e.g. Process is faster/cleaner/more accurate than Class, and both are better than Title.? Or is it just use whatever?

And what about exact match vs using regular expression? And multipe entries vs combining them?

  match_process_name: "Taskmgr"
  match_process_name: "PROCEXP64"

or:

  match_process_name: "/Taskmgr|PROCEXP64/"

Thanks.

**Comment by lars-berger** [comment]
It doesn't matter which match criteria is used to target a window. They're only run when a window is initially managed, so performance isn't really a problem. Some windows might have the same class name or process name though, so it can be useful in those cases to use multiple criteria to target a window more specifically.

```yaml
window_rules:
  # eg. only target Notepad windows that have the title "Untitled - Notepad"
  - command: "move to workspace 5"
    match_process_name: "notepad"
    match_title: "Untitled - Notepad"
```

I think the config syntax might be confusing to some. This match criteria stuff is probably the #1 thing I've been asked questions about. 

Maybe a syntax like this would be better?

```yaml
  - command: "move to workspace 5"
    match_by:
      - process_name: "notepad"
      - title: "Untitled - Notepad"
```

Or another way could be to have a property called `match_any`, which would trigger if any match criteria are true, and an alternative called `match_all`, which would combine the match criteria to be more specific (like the current behavior).

Even though it'd be more powerful, maybe it'd just be even more confusing. eg:

```yaml
   # Target notepad windows like in the above example
  - command: "move to workspace 5"
    match_all:
      - process_name: "notepad"
      - title: "Untitled - Notepad"
      
  # Target windows with either title "Untitled - Notepad" or "Untitled2 - Notepad"
  - command: "move to workspace 5"
    match_any:
      - title: "Untitled - Notepad"
      - title: "Untitled2 - Notepad"
```

Edit: by the way, I didn't even know it was valid yaml to repeat a property multiple times. Haven't tried it out before and not sure what would happen.

**Reply by maphew** [reply]
The `match_any` and `match_all` syntax makes the most sense to me at the moment. 

This probably ties into my 2nd question today too, https://github.com/lars-berger/GlazeWM/discussions/185. Maybe the threads should be combined(?)

**Reply by lars-berger** [reply]
I've never repeating `match_process_name` like you mentioned in #185, so whatever happens is unintentional. 

With the way things currently behave, this way would be the correct to define your window rule:

```yaml
window_rules:
  - command: "ignore"
    match_process_name: "/Au3Info|Taskmgr|PROCEXP64/"
```

I gotta admit i'm not a huge fan of having these big regexes like above, so that'd be an advantage of the `match_any`/`match_all` syntax. This does look better imo:

```yaml
window_rules:
  - command: "ignore"
    match_any:
      - process_name: "Au3Info"
      - process_name: "Taskmgr"
      - process_name: "PROCEXP64"
```
