### DISCUSSION TITLE
Adding more programs to ignore window_rules breaks all of them?

### DISCUSSION THREAD

**Discussion by maphew** [glzr-io/glazewm#185] [Q&A] [answered]
So, this config works to ignore both _Task Manager_ and _[AutoIt Window Info](https://www.autoitscript.com/autoit3/docs/intro/au3spy.htm)_ windows:

```
window_rules:
  - command: "ignore"
    match_process_name: "Taskmgr"
    match_process_name: "Au3Info"
```

However when I add the match below for _SysInternals Process Explorer_ all of the matching breaks, meaning Task Manager and AutoIt Window Info are no longer ignored. There are no messages recorded in `.glaze-wm\errors.log`. 

```
window_rules:
  - command: "ignore"
    match_process_name: "Taskmgr"
    match_process_name: "Au3Info"
    match_process_name: "/procexp|PROCEXP64/"
```

These also break all of them:

```
window_rules:
  - command: "ignore"
    match_process_name: "Taskmgr"
    match_process_name: "Au3Info"
    match_process_name: "procexp"
    match_process_name: "PROCEXP64"
```

```
window_rules:
  - command: "ignore"
    match_process_name: "Taskmgr"
    match_process_name: "Au3Info"
    match_process_name: "PROCEXP64"
```

This however successfully ignores all 3 programs:

```
window_rules:
  - command: "ignore"
    match_process_name: "/Au3Info|Taskmgr|PROCEXP64/"
```

So it seems `match_process_name` can only be used twice?
