### DISCUSSION TITLE
Does `match_title` support wildcards?

### DISCUSSION THREAD

**Discussion by azinsharaf** [glzr-io/glazewm#288] [Q&A] [answered]
hi, Does `match_title` support wildcards? 
I am trying to move the Brave window to an specific space if it's title **includes** `Outlook`. 
```
  - command: "move to workspace 2"
    match_process_name: "Brave"
    match_title": "Outlook"
```

**Comment by lars-berger** [comment, marked as answer]
Yep, you can use regex in the matchers, eg

```yaml
  - command: "move to workspace 2"
    match_process_name: "Brave"
    match_title": "/.*Outlook.*/"
```
