### DISCUSSION TITLE
Windows terminal 'Quake' mode

### DISCUSSION THREAD

**Discussion by ccalhoun1999** [glzr-io/glazewm#328] [Q&A] [answered]
Is there anyway to not resize the quake mode (windows + `) window of the windows terminal app? I'd like to still have normal terminal windows tiled. Not sure if this is possible though.

**Comment by ccalhoun1999** [comment]
It seems to be an issue with Terminal rather than with Glaze. If they implement profiles specific to quake mode then this should be possible.

**Comment by worldofgeese** [comment]
@ccalhoun1999 can you reopen this? I'm also interested and, as it's not resolved, I'm curious if this is possible. Can you comment, @lars-berger?

**Comment by ccalhoun1999** [comment]
@worldofgeese I can reopen it. I don't personally use quake mode anymore, but it would be nice to have working.

**Comment by aldrichtr** [comment, marked as answer]
I think I have a solution for this one:

in your config.yaml
```yaml
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'WindowsTerminal' }
        window_class: { regex: 'CASCADIA_HOSTING_WINDOW_CLASS' }
```

I found the window class name [here](https://github.com/microsoft/terminal/blob/3a06826915d11ee2124de9b35e42300e1c3f68d5/src/cascadia/WindowsTerminal/IslandWindow.cpp#L27)
