### DISCUSSION TITLE
Custom window title on Command

### DISCUSSION THREAD

**Discussion by lazuee** [glzr-io/glazewm#487] [Ideas]
Enable to add custom `window_title` on `window_rules`

```yaml
window_rules:
  - command: "set window-title 'Browser'"
    match_process_name: "vivaldi"
    match_title: "/^(?![Vv]ivaldi Settings).*$/"
  - command: "set window-title 'Browser - Settings'"
    match_process_name: "vivaldi"
    match_title: "/^(?:[Vv]ivaldi Settings).*$/"

bar:
  components_center:
    - type: "window title"
      label: "{window_title}" # Browser <-- if vivaldi focused
```
