### DISCUSSION TITLE
Blender3D keybinding

### DISCUSSION THREAD

**Discussion by OmarGonD** [glzr-io/glazewm#717] [Q&A]
I want to associate Blender to the keybiding: alt+b

I've tried using window_rules:

   - commands: [exec "C:\Program Files\Blender Foundation\Blender 4.2\blender-launcher.exe"]
     binding: ['alt+b']
     
But getting error:
 
 windows_rules[1].commands: unrecognized subcommand at line 164 column 15.
     
```
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      - window_process: { equals: 'PowerToys.PowerAccent' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

   - commands: [exec "C:\Program Files\Blender Foundation\Blender 4.2\blender-launcher.exe"]
     binding: ['alt+b']
```
