### DISCUSSION TITLE
Does Anyone has same error in zebar workspace button click event, when js import?

### DISCUSSION THREAD

**Discussion by ShortArrow** [glzr-io/glazewm#816] [Q&A] [answered]
# Error

```text
[Window Title]
Non-fatal: Error in template/glazewm_workspaces

[Content]
Failed to fetch dynamically imported module: http://asset.localhost/C%3A%5CUsers%5Cwho%5C.glzr%5Czebar%5Cscript.js

[OK]
```

# Config

config.yaml

```yaml

    template/glazewm_workspaces:
      styles: |
        display: flex;
        align-items: center;

        .workspace {
          background: rgb(255 255 255 / 5%);
          margin-right: 4px;
          padding: 4px 8px;
          color: rgb(255 255 255 / 90%);
          border: none;
          border-radius: 2px;
          cursor: pointer;

          &.displayed {
            background: rgb(255 255 255 / 15%);
          }

          &.focused,
          &:hover {
            background: rgb(75 115 255 / 50%);
          }
        }
      providers: ['glazewm']
      events:
         - type: 'click'
           fn_path: 'script.js#focusWorkspace'
           selector: '.workspace'
      template: |
        @for (workspace of glazewm.currentWorkspaces) {
          <button
            class="workspace {{ workspace.hasFocus ? 'focused' : '' }} {{ workspace.isDisplayed ? 'displayed' : '' }}"
            id="{{ workspace.name }}"
          >
            {{ workspace.displayName ?? workspace.name }}
          </button>
        }
```

script.js

```js
export function focusWorkspace(event, context) {
  console.log('Focus button clicked!', event, context);
  const id = event.target.id;
  context.providers.glazewm.focusWorkspace(id);
}
```

```pwsh
❯ ls ~/.glzr/zebar

    Directory: C:\Users\who\.glzr\zebar

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          2024/08/07    13:56              0 config.yaml -> C:\Users\who\Documents\GitHub\dotfiles\zebar\config.yaml
la---          2024/08/07    13:56              0 script.js -> C:\Users\who\Documents\GitHub\dotfiles\zebar\script.js
la---          2024/08/07    13:56              0 start.bat -> C:\Users\who\Documents\GitHub\dotfiles\zebar\start.bat
la---          2024/08/07    13:56              0 start.sh -> C:\Users\who\Documents\GitHub\dotfiles\zebar\start.sh
```
