### DISCUSSION TITLE
Getting Ueli working

### DISCUSSION THREAD

**Discussion by rputikar** [glzr-io/glazewm#824] [Q&A]
how to get ueli keystroke launcher (https://ueli.app/) working with glazeWM? Once I launch glazeWM, ueli stops working (I can't launch it via shortcut (Alt Space) or through windows menu.

**Comment by chouhbi** [comment]
Try this:

In your config file add  `- window_title: { equals: 'Ueli' }` under  window_rules.

It would look something like this:
```
window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores any Ueli windows.
      - window_title: { equals: 'Ueli' }                 <---- this
```
