### DISCUSSION TITLE
How do i add exceptions for programs in a specific folder?

### DISCUSSION THREAD

**Discussion by BlitzVI** [glzr-io/glazewm#837] [Q&A]
i've recently installed glazewm and it seems to help alot with my workflow but when i try to play games like cyberpunk 2077 it messes up the way the game is full screened. I see there's a way to ignore rules for 3rd party apps in the config file but i cant seem to make it work. I have an entire folder filled with game shortcuts so maybe i could just add an exception for that specific folder and it'll be fixed?
Any help is greatly appreciated!

**Comment by purnasatria** [comment]
I'm using v3.6.0 and it works perfectly fine for playing games in full screen. I don't add any rules in the config though.
For adding rules, I use Autoit3 Window Spy to get the application name/class.
<details>
<summary>Here my config, hopes it help</summary>

```yaml
general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation and keeps them
  # visible in the taskbar.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "20px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "60px"
    right: "20px"
    bottom: "20px"
    left: "20px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#a6da95"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }
      - window_process:
          { regex: "Taskmgr|ScreenClippingHost|premeeng|explorer" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      - window_title: { equals: "Data Sources and Drivers" }
      - window_title: { equals: "Setup" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["f24+shift+p"]
        # bindings: ['alt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["f24+h", "f24+left"]
    # bindings: ['alt+h', 'alt+left']
  - commands: ["focus --direction right"]
    bindings: ["f24+l", "f24+right"]
    # bindings: ['alt+l', 'alt+right']
  - commands: ["focus --direction up"]
    bindings: ["f24+k", "f24+up"]
    # bindings: ['alt+k', 'alt+up']
  - commands: ["focus --direction down"]
    bindings: ["f24+j", "f24+down"]
    # bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["f24+shift+h", "f24+shift+left"]
    # bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ["move --direction right"]
    bindings: ["f24+shift+l", "f24+shift+right"]
    # bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ["move --direction up"]
    bindings: ["f24+shift+k", "f24+shift+up"]
    # bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ["move --direction down"]
    bindings: ["f24+shift+j", "f24+shift+down"]
    # bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["f24+u"]
    # bindings: ['alt+u']
  - commands: ["resize --width +2%"]
    bindings: ["f24+p"]
    # bindings: ['alt+p']
  - commands: ["resize --height +2%"]
    bindings: ["f24+o"]
    # bindings: ['alt+o']
  - commands: ["resize --height -2%"]
    bindings: ["f24+i"]
    # bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["f24+r"]
    # bindings: ['alt+r']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["f24+shift+p"]
    # bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["f24+v"]
    # bindings: ['alt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["f24+space"]
    # bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["f24+shift+space"]
    # bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["f24+t"]
    # bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["f24+f"]
    # bindings: ['alt+f']

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["f24+m"]
    # bindings: ['alt+m']

  # Close focused window.
  - commands: ["close"]
    bindings: ["f24+shift+q"]
    # bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["f24+shift+e"]
    # bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["f24+shift+r"]
    # bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["f24+shift+w"]
    # bindings: ['alt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ['shell-exec alacritty']
  #   bindings: ['f24+enter']
  - commands: ["shell-exec wt"]
    bindings: ["f24+enter"]
    # bindings: ['alt+enter']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["f24+s"]
    # bindings: ['alt+s']
  - commands: ["focus --prev-workspace"]
    bindings: ["f24+a"]
    # bindings: ['alt+a']

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["f24+d"]
    # bindings: ['alt+d']

  # Change focus to a workspace defined in `workspaces` config.
  # - commands: ['focus --workspace 1']
  #   bindings: ['alt+1']
  # - commands: ['focus --workspace 2']
  #   bindings: ['alt+2']
  # - commands: ['focus --workspace 3']
  #   bindings: ['alt+3']
  # - commands: ['focus --workspace 4']
  #   bindings: ['alt+4']
  # - commands: ['focus --workspace 5']
  #   bindings: ['alt+5']
  # - commands: ['focus --workspace 6']
  #   bindings: ['alt+6']
  # - commands: ['focus --workspace 7']
  #   bindings: ['alt+7']
  # - commands: ['focus --workspace 8']
  #   bindings: ['alt+8']
  # - commands: ['focus --workspace 9']
  #   bindings: ['alt+9']
  - commands: ["focus --workspace 1"]
    bindings: ["f24+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["f24+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["f24+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["f24+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["f24+5"]
  - commands: ["focus --workspace 7"]
    bindings: ["f24+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["f24+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["f24+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["f24+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  # - commands: ['move-workspace --direction left']
  #   bindings: ['alt+shift+a']
  # - commands: ['move-workspace --direction right']
  #   bindings: ['alt+shift+f']
  # - commands: ['move-workspace --direction up']
  #   bindings: ['alt+shift+d']
  # - commands: ['move-workspace --direction down']
  #   bindings: ['alt+shift+s'
  # - commands: ['move-workspace --direction left']
  #   bindings: ['f24+shift+a']
  # - commands: ['move-workspace --direction right']
  #   bindings: ['f24+shift+f']
  - commands: ["move-workspace --direction up"]
    bindings: ["f24+shift+d"]
  - commands: ["move-workspace --direction down"]
    bindings: ["f24+shift+s"]

  # Move focused window to a workspace defined in `workspaces` config.
  # - commands: ['move --workspace 1', 'focus --workspace 1']
  #   bindings: ['alt+shift+1']
  # - commands: ['move --workspace 2', 'focus --workspace 2']
  #   bindings: ['alt+shift+2']
  # - commands: ['move --workspace 3', 'focus --workspace 3']
  #   bindings: ['alt+shift+3']
  # - commands: ['move --workspace 4', 'focus --workspace 4']
  #   bindings: ['alt+shift+4']
  # - commands: ['move --workspace 5', 'focus --workspace 5']
  #   bindings: ['alt+shift+5']
  # - commands: ['move --workspace 6', 'focus --workspace 6']
  #   bindings: ['alt+shift+6']
  # - commands: ['move --workspace 7', 'focus --workspace 7']
  #   bindings: ['alt+shift+7']
  # - commands: ['move --workspace 8', 'focus --workspace 8']
  #   bindings: ['alt+shift+8']
  # - commands: ['move --workspace 9', 'focus --workspace 9']
  #   bindings: ['alt+shift+9']
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["f24+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["f24+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["f24+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["f24+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["f24+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["f24+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["f24+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["f24+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["f24+shift+9"]
```

</details>
