### DISCUSSION TITLE
Rules for PowerPoint Presenter View

### DISCUSSION THREAD

**Discussion by iamwillbar** [glzr-io/glazewm#918] [General]
Does anyone have an example config for ensuring that the presentation and presenter view are in different workspaces attached to different monitors?

**Comment by eriklieben** [comment]
Not an expert on this, but this worked for me; don't know if this can be done better, but it's at least in workable state now :-) I had a strange second smaller view of the presentation before.

From what I understand from it, `screenClass` seems to be the fullscreen projection of the slides when in presentation mode, so that always moves to a workspace on my second monitor. And the presenter view is `PodiumParent` that now moves to a workspace on my first monitor.

```yaml
window_rules:   
  - commands: ['move --workspace 6']
    match:
      - window_process: { equals: 'POWERPNT' }
        window_class: { equals: 'screenClass'}
  - commands: ['move --workspace 1']
    match:
      - window_process: { equals: 'POWERPNT' }
        window_class: { equals: 'PodiumParent'}
```
