### DISCUSSION TITLE
Can i set a hotkey to toggle window opacity??

### DISCUSSION THREAD

**Discussion by YoungTaro** [glzr-io/glazewm#995] [Q&A]
Hi im very new to this stuff and a very low understanding of config files i wanted to know if there is a way to toggle window opacity on/off for gaming or rendering on blender

**Comment by n-crespo** [comment]
```yaml
keybindings:
  - commands: ["set-transparency --opacity 0.5"]
    bindings: ["alt+o"]

  - commands: ["set-transparency --opacity 1"]
    bindings: ["alt+shift+o"]
```
