### DISCUSSION TITLE
Assigning Workspaces

### DISCUSSION THREAD

**Discussion by nate241988** [glzr-io/glazewm#999] [Q&A]
I have no experience in programming. 
I have been using GlazeWM for a few weeks and like it. That said, I have been attempting to customize it a bit. I have been able to get custom keybindings to open what I use most, and I even added them to the startup command so they launch when I start the app. I have been trying to accomplish two things that I haven't been able to find the answers to.

1. When I open the browser (Firefox) using key bindings that point to a website, they will not open in a new window just add a new tab to the current window. However, if I use the keybinding to open a browser that is not going to a website, it will open new windows every time.

This will open a new window each time.
 ```
- commands: ['shell-exec firefox'] 
   bindings: ['alt+q']
```

This will only open a tab and not a new window.
```
- commands: ['shell-exec firefox https://www.youtube.com/'] 
  bindings: ['alt+z']
```

2. I would like to assign a specific window to a predetermined workspace. I have found a few examples on the various GitHub forks, but none have worked.
I saw the example given and tried to use it and modify it for what I was attempting. 
```
window_rules:
- commands: ["move --workspace 1"] 
  match:
    # Move browsers to workspace 1. 
     - window_process: { regex: "msedge|brave|chrome" }
```

After playing around with it a lot and failing, this is what I am using that won't give me an error when loading the config. However, it still stacks the web pages in tabs and opens all apps on the same workspace.
```
window_rules:
 - commands: ["move --workspace 1"]
   match:
     # Move browsers to workspace 1.
      - window_process: { regex: "firefox.exe" }
        window_title: { regex: ".*http://www.youtube/com.*" }
      - window_process: { regex: "firefox.exe" }
        window_title: { regex: ".*http://reddit/com.*" }

 - commands: ["move --workspace 2"]
   match:
     # Move browsers to workspace 2.
      - window_process: { regex: "firefox.exe" }

 - commands: ["move --workspace 3"]
   match:
      # Move VMware to workspace 3.
      - window_process: { regex: "firefox.exe" }
        window_title: { regex: ".*https://remotedesktop.google.com/access.*" }
 - commands: ["move --workspace 4"]
   match:
     # Move VS Code to workspace 4.
      - window_process: { regex: "vmware.exe" }

 - commands: ["move --workspace 5"]
   match:
     # Move CMD to workspace 5.
      - window_process: { regex: "code.exe" }
      
   match:
     # Move CMD to workspace 5.
      - window_process: { regex: "code.exe" }
window_rules:
 - commands: ["move --workspace 1"]
   match:
     # Move browsers to workspace 1.
      - window_process: { regex: "firefox.exe" }
        window_title: { regex: ".*http://www.youtube/com.*" }
      - window_process: { regex: "firefox.exe" }
        window_title: { regex: ".*http://reddit/com.*" }


 - commands: ["move --workspace 2"]
   match:
     # Move browsers to workspace 2.
      - window_process: { regex: "firefox.exe" }


 - commands: ["move --workspace 3"]
   match:
      # Move VMware to workspace 3.
      - window_process: { regex: "firefox.exe" }
        window_title: { regex: ".*https://remotedesktop.google.com/access.*" }
 - commands: ["move --workspace 4"]
   match:
     # Move VS Code to workspace 4.
      - window_process: { regex: "vmware.exe" }


 - commands: ["move --workspace 5"]
   match:
     # Move CMD to workspace 5.
      - window_process: { regex: "code.exe" }
      
   match:
     # Move CMD to workspace 5.
      - window_process: { regex: "code.exe" }
```

Any help or ideas would be greatly appreciated, but please remember that I do not understand much of this; I am just trying to learn as I go.

**Comment by SvenSchneiderDVAG** [comment]
Yeah, that's the biggest feature I'm missing. Permanently assigning of apps to workspaces. Tried above solutions, wasn't succesful ..

**Reply by SvenSchneiderDVAG** [reply]
I did successfully assign my Brave Browser to workspace 1 with this:

```
window_rules:
  - commands: ['move --workspace 1']
      match:
        # Move browsers to workspace 1.
        - window_process: { regex: 'msedge|brave|chrome|firefox' }
          window_class: { equals: 'Chrome_WidgetWin_1' }`
```
