### ISSUE TITLE
[Bug] - Not Opening

### ISSUE THREAD

**Issue by ishagg04** [glzr-io/glazewm#1002]
### Describe the bug

If I click to open it, this happens:

![Image](https://github.com/user-attachments/assets/3cbae135-1f84-4f04-aeb0-12c4af257546)
![Image](https://github.com/user-attachments/assets/5e4f1d2c-e57c-4a70-93e7-d2a6222f1942)

### Stack trace or error logs (if applicable)

```shell

```

### Version number

Latest

**Comment by Im-shamo** [comment]
Have you install zebar

**Comment by Im-shamo** [comment]
In the config remove zebar in startup and shutdown commands.
```yaml
general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ["shell-exec zebar"] # <- here

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]  # <- here
```
