### ISSUE TITLE
[Bug] Unexpected Blank Window Appears When Running Hancom Office on Windows 10

### ISSUE THREAD

**Issue by Kang-geophysics** [glzr-io/glazewm#1016]
#### **Issue Description**
When running Hancom Office (a Korean word processing software like MS Office) on Windows 10 with GlazeWM enabled, an unintended blank window appears on the right side of the screen (as shown in the attached screenshot). This window does not contain any content but remains open.

#### **Steps to Reproduce**
1. Install and enable GlazeWM on Windows 10.
2. Open Hancom Office (HWP).
3. Observe an unexpected blank window appearing on the right side.

#### **Expected Behavior**
Only the main Hancom Office window should be displayed, without any additional blank windows.

#### **Observed Behavior**
A blank window appears on the right side, which does not close automatically.

#### **Possible Causes**
- GlazeWM may be misinterpreting Hancom Office's UI elements as separate windows.
- There may be a conflict between GlazeWM's tiling mechanism and Hancom Office's window management.
- Windows 10's display scaling or multi-monitor setup might be contributing to the issue.

#### **Workarounds Tried**
- Running Hancom Office in compatibility mode (Windows 7/8) → Issue persists.
- Stopping GlazeWM (`glaze.exe stop`) before launching Hancom Office → Issue disappears.
- Checking for ignored window settings in `glazewm.toml` → No relevant rules found.

#### **Additional Information**
- **GlazeWM Version:** [Provide your version]
- **Windows Version:** Windows 10 [Your build number]
- **Hancom Office Version:** [Provide version]

Is there a way to exclude specific windows from GlazeWM's tiling mechanism? Any suggestions would be appreciated.

Thank you!

![Image](https://github.com/user-attachments/assets/58c2ffc6-b016-4feb-b78c-8fd3196c04c2)

### Stack trace or error logs (if applicable)

```shell

```

### Version number

v3.8.1

**Comment by Kang-geophysics** [comment]
I solved this using ignore rules by including this.
I can check the class of this with "window spy" of autohotkey!
``` 
- window_class: { regex: 'MessageWindowClass'}
```

**Comment by tryfasting** [comment]
@Kang-geophysics Thank you for sharing the solution! It helped others too.

I noticed a small syntax issue in the config: `equals` needs a colon after it, like `equals: 'Hwp'`. 
I tested it and it works perfectly. Thanks again!

Corrected version:
```yaml
- window_class: { regex: 'MessageWindowClass' }
  window_process: { equals: 'Hwp' }
- window_class: { regex: 'MessageWindowClass' }
  window_process: { equals: 'Hpdf' }
- window_class: { regex: 'MessageWindowClass' }
  window_process: { equals: 'Hword' }
- window_class: { regex: 'MessageWindowClass' }
  window_process: { equals: 'HCell' }
- window_class: { regex: 'MessageWindowClass' }
  window_process: { equals: 'HShow' }
```

For Korean Users :
@Kang-geophysics님 해결법 공유 감사합니다. 
equals: 로 콜론(:)이 빠져 있는 것 같아 comment 남깁니다.
위 수정 버전으로 테스트 완료했습니다!
