### ISSUE TITLE
[Bug] Windows Run Command/Dialog (Win+R) doesn't want to stay on top

### ISSUE THREAD

**Issue by slava110** [glzr-io/glazewm#1022]
### Describe the bug

Hi. I have `focus_follows_cursor` option enabled. I also have window rule for Run Command to be shown on top. However, when I move cursor between different windows in the background, Run Command dialog gets behind all other windows and I cannot access it. If I focus on Run Command window again using taskbar and try to move cursor to it, focus changes again if I have windows open, so it hides behind windows again. It makes Run Command inaccessible with `focus_follows_cursor` option set to `true`

### Reproduction

Set `focus_follows_cursor` to `true`, add window rule (you can add it for explorer since it's explorer process if I understand correctly):
```yaml
- commands: ['set-floating --shown-on-top=true --centered=true']
    match:
      - window_process: { equals: 'explorer' }
```
Run GlazeWM, open at least two windows, launch Run Command using Win+R keybinding, and move your cursor between windows in the background. Run Command dialog will hide between all other windows.

### Stack trace or error logs (if applicable)

```shell

```

### Version number

3.8.1
