### ISSUE TITLE
[Feature Request] Ignore focus for popup notifcations

### ISSUE THREAD

**Issue by Taloonys** [glzr-io/glazewm#1036]
### Describe the problem/motivation

Sitation: 
* Fullscreen game
* Steam notification appears at bottom right
* It steals focus, so now you have to alt+tab back

Also:
* I've experienced same stuff with some device's software. So... Disabling steam notifications isn't really enough...

### Describe the solution you'd like

```yaml
window_rules:
  - commands: ['no-focus']:
    match:
      - window_title: #...
```

### Alternatives considered

Focus some apps only by clicking or navigating to them manually
```yaml
window_rules:
  - commands: ['only-manual-focus']:
    match:
      - window_title: #...
```
