### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Taloonys** [glzr-io/glazewm#1037]
### Describe the problem/motivation

2 monitors, one is 1440p, one is 1080p
* Have 2 window desktops (Win + Tab, and `Win` + `Ctrl` + `<-` / `->` navigation)
* On second desktop launched VMware fullscreened + Cyclic monitors
* navigate to another desktop (without VMware) and navigate back
* now it's sth like this 
![Image](https://github.com/user-attachments/assets/db8802b4-db97-46e1-90d3-8ac7a399ef86)

issue comes with:
```yaml
  - commands: ["set-floating"]
    match:
      # VMware fix
      - window_title: { regex: '.* - VMware Workstation$' }
```
with the same *match* stuff in
```yaml
  - commands: ['ignore']
    # ..
```
everything is ok, but if i use transparency for unfocused windows...

### Describe the solution you'd like

`ignore` windows don't inherit inactive window behavior

### Alternatives considered

Another ignore command-group? like:
```yaml
window_rules:
  - commands["detach"]
  # or
  - command["ignore"]
    behavior:
    # if described, it doesn't inherit inactive-windows behavior
  match:
  - commands["ingore"]:
    # ...
```
