### ISSUE TITLE
[Bug] Powertoy Command Pallete Ignore doesnt work

### ISSUE THREAD

**Issue by elbiazo** [glzr-io/glazewm#1038]
### Describe the bug

Similar to powertoy run, there is newer one called powertoy command pallete.

I try to make it float by doing but it doesn't seem to work. it should be floating.

```
          # Ignore Command Pallete
          - window_process: { equals: "Command Palette" }
          - window_process: { equals: "Microsoft.CmdPal.UI" }
```

### Version number

glazewm 3.8.1

**Comment by elbiazo** [comment]
seems to work via `- window_title: { regex: ".*Palette.*" }`

**Comment by danymat** [comment]
Hello, how did you find the `equals` name ? I would like to not use this kind of regex that seems very wide

**Comment by elbiazo** [comment]
> Hello, how did you find the `equals` name ? I would like to not use this kind of regex that seems very wide. Maybe try this on match see if this work.

Hey this is what I did.

```
- window_title: { regex: "Command Palette" }
```

**Comment by Kang-geophysics** [comment]
In my case,
```
- window_app: { regex: '^Microsoft\.CmdPal\.UI\.exe$' } 
```

**Comment by R4GN3R0** [comment]
i dont get this working either...

**Comment by Aeitto** [comment]
> i dont get this working either...
> 
> my code
> 
> ```
> window_rules:
>   - commands: ['ignore']
>     match:
>       - window_process: { equals: 'zebar' }
>       - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
>         window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
>       - window_process: { equals: 'PowerToys' }
>         window_class: { regex: 'HwndWrapper[PowerToys\.PowerAccent.*?]' }
>       - window_process: { equals: 'PowerToys' }
>         window_title: { regex: '.*? - Peek' }
>       - window_process: { equals: 'Lively' }
>         window_class: { regex: 'HwndWrapper' }
>       - window_process: { equals: "Command Palette" }
>       - window_title: { regex: ".*Palette.*" }
>       - window_title: { regex: "Command Palette" }   
> ```

Thank you. Ignore works but depending on current tiling the whole Command Palette gets stretched.
I tried to make it initial state as fload but none of command works.
Tried float, floating, set_float, set_floating etc.
```
  - commands: ['set_floating']
    match:
      - window_process: { equals: "Command Palette" }
      - window_title: { regex: ".*Palette.*" }
      - window_title: { regex: "Command Palette" }  
```

any clue to make it pop up on center just as without glaze?

**Comment by FilipRuman** [comment]
Also can't get this to work in any way

**Comment by Kang-geophysics** [comment]
Try to check the class of window using "Window Spy" of auto hotkey.

**Comment by dosoft** [comment]
> Also can't get this to work in any way

This worked for me:

```yaml
window_rules:
  - commands: ['set-floating']
    match:
      - window_title: { equals: 'Command Palette' }
```

Hope this helps.
