### ISSUE TITLE
[Bug] Zoom crashes

### ISSUE THREAD

**Issue by jericjan** [glzr-io/glazewm#1097]
### Describe the bug

It appears Zoom crashes as soon as I join a meeting. Funny enough the ongoing stream does continue to play while the entire UI is unresponsive. I had to ignore it in the config.

Using Windows 10 v2004 if that's needed.

```
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'Zoom' }
      - window_process: { equals: 'zWebview2Agent' }
```

### Reproduction

1. Run GlazeWM
2. Set windows to default to tiling
3. Join a Zoom meeting
4. Zoom crashes

### Stack trace or error logs (if applicable)

```shell

```

### Version number

3.8.1
