### ISSUE TITLE
[Bug] Setting keep_alive for all workspaces on multiple monitors results in a startup error

### ISSUE THREAD

**Issue by Video-Nomad** [glzr-io/glazewm#1099]
### Describe the bug

Setting `keep_alive: true` for all workspaces results in a fatal error `At least 1 workspace is required per monitor` during GlazeWM startup on a multi-monitor setup.

### Reproduction

```yaml
workspaces:
  - name: "1"
    bind_to_monitor: 1
    keep_alive: true
  - name: "2"
    bind_to_monitor: 1
    keep_alive: true
  - name: "3"
    bind_to_monitor: 1
    keep_alive: true
  - name: "4"
    bind_to_monitor: 1
    keep_alive: true
  - name: "5"
    bind_to_monitor: 1
    keep_alive: true
  - name: "6"
    bind_to_monitor: 1
    keep_alive: true
  - name: "7"
    bind_to_monitor: 1
    keep_alive: true
  - name: "8"
    bind_to_monitor: 0
    keep_alive: true
  - name: "9"
    bind_to_monitor: 0
    keep_alive: true
  - name: "10"
    bind_to_monitor: 0
    keep_alive: true
```

### Stack trace or error logs (if applicable)

```shell
No workspace config available to activate workspace.
```

### Version number

3.9.0

**Comment by SlyCedix** [comment]
Having a similar issue here, but I'm not sure keep_alive is the culprit, since even after changing one of my workspaces to `keep_alive: false` the error still occurred:

```yml
workspaces:
  - name: "1:1"
    display_name: "I:1"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:2"
    display_name: "II"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:3"
    display_name: "III"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:4"
    display_name: "IV"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:5"
    display_name: "V"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:6"
    display_name: "VI"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:7"
    display_name: "VII"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:8"
    display_name: "VIII"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:9"
    display_name: "IX"
    keep_alive: true
    bind_to_monitor: 0
  - name: "1:0"
    display_name: "X"
    keep_alive: true
    bind_to_monitor: 0

  - name: "2:1"
    display_name: "I:2"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:2"
    display_name: "II"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:3"
    display_name: "III"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:4"
    display_name: "IV"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:5"
    display_name: "V"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:6"
    display_name: "VI"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:7"
    display_name: "VII"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:8"
    display_name: "VIII"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:9"
    display_name: "IX"
    keep_alive: true
    bind_to_monitor: 1
  - name: "2:0"
    display_name: "X"
    keep_alive: true
    bind_to_monitor: 1
```

I was able to (sort of) work around it by adding one additional workspace on monitor 2, despite only having monitors 0 and 1.

```yml
  - name: "DUMMY"
    display_name: "DUMMY"
    keep_alive: false
    bind_to_monitor: 2
```

Once I get that up and running though, bind_to_monitor is not respected for workspace 2:1 and appears on monitor 0 instead.
```yml
  - name: "2:1"
    display_name: "I:2"
    keep_alive: true
    bind_to_monitor: 1
```

**Comment by OnlYKai** [comment]
mine is
```yaml
workspaces:
  - name: '1'
    bind_to_monitor: 0
    keep_alive: true
  - name: '2'
    bind_to_monitor: 1
    keep_alive: true
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
```
and this causes glaze to start with workspaces 1, 3 on monitor 0 and 2, 4 on monitor 1

so it seems like keep_alive workspaces arent seen as existing workspaces on startup, resulting in `At least 1 workspace is required per monitor` if all are `keep_alive: true` and additional workspaces being opened on each monitor in my case
