### ISSUE TITLE
[Bug] Some applications start as floating by default even without rules applied

### ISSUE THREAD

**Issue by Video-Nomad** [glzr-io/glazewm#1100]
### Describe the bug

Some applications start as floating by default. A good example is `steam` or `telegram`. Even without any rules applied it will start as floating, but will tile if explicitly set to `set-tiling`.

### Reproduction

No config for steam starts steam as floating.

This starts the entire steam application as floating:
```
  - commands: [ "set-floating" ]
    match:
      - window_process: { equals: "steamwebhelper" }
        window_title: { not_equals: "Steam" }
```

This tiles it properly:
```
  - commands: ["set-tiling"]
    match:
      - window_process: { equals: 'steamwebhelper' }
```

### Stack trace or error logs (if applicable)

```shell
No errors
```

### Version number

3.9.0
