### ISSUE TITLE
[Feature Request] Resize windows in a direction

### ISSUE THREAD

**Issue by Miitto** [glzr-io/glazewm#1110]
### Describe the problem/motivation

Currently the resize commands work by increasing width / height by a value. The following config:
```yaml
- commands: ['resize --width -2%']
  bindings: ['left']
- commands: ['resize --width +2%']
  bindings: ['right']
- commands: ['resize --height +2%']
  bindings: ['up']
- commands: ['resize --height -2%']
  bindings: ['down']
```
will result in a window on the right hand of the screen growing to the left by pressing `right`.

### Describe the solution you'd like

Allow the resize command to take a direction to grow / shrink the focused window in a direction.
```yaml
- commands: ['resize --left 2%']
  bindings: ['alt+left']
- commands: ['resize --right 2%']
  bindings: ['alt+right']
- commands: ['resize --up 2%']
  bindings: ['alt+up']
- commands: ['resize --down 2%']
  bindings: ['alt+down']
```
which would allow a window on the right of the screen to grow when pressing left, and a window on the left of the screen to grow when pressing right.

In the case of more than two windows in a workspace, `width` and `height` would grow from the center, and the directional commands would only grow in that direction.

This would result in behavior akin to other programs such as `tmux`.
