### ISSUE TITLE
[Bug] default Zebar ignore window_rule ignores ALL zebar windows

### ISSUE THREAD

**Issue by akinevz0** [glzr-io/glazewm#1118]
### Describe the bug

Zebar settings window gets ignored by wm.

### Reproduction

```yaml
window_rules:
  - commands: ['ignore']
    match:
    - window_process: { equals: 'zebar' }
```

### Stack trace or error logs (if applicable)

```shell

```

### Version number

3.9.1

**Comment by akinevz2** [comment]
```yaml
window_rules:
  - commands: ['ignore']
    match:
    - window_process: { equals: 'zebar' }
      window_title: { regex: 'Zebar - .*' }
```

the above snippet only ignores bar windows as their title is in the format of "Zebar - foo", and the settings window's format is "Settings - Zebar".
