### ISSUE TITLE
[Feature Request] Ability to temporarily disable GlazeWM via keybind

### ISSUE THREAD

**Issue by hazre** [glzr-io/glazewm#201]
Have an ablity to toggle GlazeWM on/off for cases like when you want to play games or unexpected behavior happens. (until something like #70 is fixed)

**Comment by dahamond** [comment]
A temporary solution I use is using the new binding mode feature. Add a binding mode that has only one keybinding - to exit the binding mode. You can then set a keybinding to enter the new binding mode and use it every time you need to disable GlazeWM.

**Comment by hazre** [comment]
> A temporary solution I use is using the new binding mode feature. Add a binding mode that has only one keybinding - to exit the binding mode. You can then set a keybinding to enter the new binding mode and use it every time you need to disable GlazeWM.

could you share you setup? I'm not fully sure if I can follow.

**Comment by dahamond** [comment]
Binding modes:
> When a binding mode is active, only the keybindings defined for that binding mode are available (all other keybindings are disabled).

I make the binding mode:
```yaml
binding_modes:
  - name: "disabled"
    keybindings:
      - command: "binding mode none" # command to exit the binding mode
        bindings: ["Alt+Shift+Escape"] # use whatever keybinding that won't interfere while you play games etc.
```

Then in my keybindings, I make a keybinding to enter the binding mode:
```yaml
keybindings:
  - command: "binding mode disabled"
    binding: "Alt+N"
```

Basically, this disables all other other GlazeWM keybindings except for `Alt+Shift+Esc` which enables all GlazeWM keybindings again.
