### ISSUE TITLE
how do i manage offset_y

### ISSUE THREAD

**Issue by hrdkmishra** [glzr-io/glazewm#348]
![image](https://github.com/lars-berger/GlazeWM/assets/87580981/3f0ae2be-8073-4fb0-ab09-ad03f48dc210)

what im trying to do is move the bar into win11 task bar like you see but the issue is you can see the space above the window and below how do i remove that

```
bar:
  height: "30px"
  position: "bottom"
  opacity: 1
  background: "black"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "0px"
  offset_x: "800px"
  offset_y: "30px"
  border_radius: "0px"
```
