### ISSUE TITLE
Workspaces hover property

### ISSUE THREAD

**Issue by antonioepuglisiRHA** [glzr-io/glazewm#449]
I can't seem to find a way to change the color of the workspace button, these are my configs.

``` yaml
- type: "workspaces"
  # current active workspace
  focused_workspace_background: *base
  focused_workspace_foreground: *yellow
  # inactive, but displayed on other monitor workspace
  displayed_workspace_background: *base
  foreground: *peach
  font_weight: "800"
  # inactive workspace
  default_workspace_background: "transparent"
```      
![image](https://github.com/glazerdesktop/GlazeWM/assets/62648040/a20256c9-bbcc-497b-95ae-233cb502c31d)
I also checked the source code and I couldn't understand at first glance how these properties are handled, or if what I'm asking is possible at all.
