### ISSUE TITLE
[Bug] Unexpected overflow notification window behavior

### ISSUE THREAD

**Issue by AnthonyCalandra** [glzr-io/glazewm#486]
Hi there,

Wondering if anybody else has ran into this issue before and came up with a solution. Most of the time* when I click the expander in the system tray, the overflow window spawns on the top left corner of my window. Strangely, when I click on a system tray icon such as volume, its window spawns on the very top right corner.

*Sometimes, and I mean very rarely, it appears in the default/correct place, as if Glaze isn't running.

Click expander:
![image](https://github.com/glazerdesktop/GlazeWM/assets/952574/fa3336ff-1d4b-4340-a958-6fcd22b3207f)

The overflow notifications window appears in the top left corner:
![image](https://github.com/glazerdesktop/GlazeWM/assets/952574/00c00247-376b-4dc0-a6b7-6246a581b9d6)

Here's the class hierarchy in Spy++:
![image](https://github.com/glazerdesktop/GlazeWM/assets/952574/f4880b44-c9b2-45eb-8bac-d5fd909a37f0)

I've tried setting these to be ignored in my config (with various attempts) but nothing changes.

I'm thinking this might not even be detected by Glaze since I don't see any messages when I run the app in the terminal when I open the overflow notifications window.

**Environment**

* Windows 10 Pro 22H2 19045.3803
* GlazeWM version 2.0.3
* Here's my current config:
```yaml
general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follow_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: false

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "10px"

  # Gap between windows and the screen edge.
  # Should match padding of bar components.
  outer_gap: "0 10px 0 10px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#FFD866"

  inactive:
    enabled: false
    color: "#ff0000"

bar:
  height: "30px"
  position: "top"
  opacity: 1.0
  background: "#2D2A2E00"
  foreground: "#FCFCFAFF"
  font_family: "CaskadyiaCove Nerd Font"
  font_size: "14px"
  # Left/right padding should match gaps.
  padding: "4px 10px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_foreground: "#403E41FF"
      focused_workspace_background: "#FFD866FF"
      displayed_workspace_background: "#FCFCFAFF"
      default_workspace_foreground: "#FCFCFAFF"
  components_center:
    - type: "window title"
  components_right:
    - type: "system tray"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "network"
      label_no_internet: "󰤮"
      label_ethernet: "󰈀"
      label_wifi_strength_0: "󱚺"
      label_wifi_strength_25: "󰤟"
      label_wifi_strength_50: "󰤢"
      label_wifi_strength_75: "󰤥"
      label_wifi_strength_100: "󰤨"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "memory"
      label: "RAM {percent_usage}%"
      refresh_interval_ms: 1000
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "cpu"
      label: "CPU {percent_usage}%"
      refresh_interval_ms: 1000
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "hh:mm tt  ddd MMM d"

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  - command: "ignore"
    match_class_name: "/NotifyIconOverflowWindow/"

  # Do not manage picture-in-picture windows for browsers.
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  - command: "set floating"
    match_process_name: "/^(?!WindowsTerminal$).*/"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["LWin+Alt+Left"]
  - command: "focus right"
    bindings: ["LWin+Alt+Right"]
  - command: "focus up"
    bindings: ["LWin+Alt+Up"]
  - command: "focus down"
    bindings: ["LWin+Alt+Down"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["LWin+Alt+Shift+H", "LWin+Alt+Shift+Left"]
  - command: "move right"
    bindings: ["LWin+Alt+Shift+L", "LWin+Alt+Shift+Right"]
  - command: "move up"
    bindings: ["LWin+Alt+Shift+K", "LWin+Alt+Shift+Up"]
  - command: "move down"
    bindings: ["LWin+Alt+Shift+J", "LWin+Alt+Shift+Down"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "LWin+Alt+U"
  - command: "resize width +2%"
    binding: "LWin+Alt+P"
  - command: "resize height +2%"
    binding: "LWin+Alt+O"
  - command: "resize height -2%"
    binding: "LWin+Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "LWin+Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "LWin+Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "LWin+Alt+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "LWin+Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "LWin+Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "LWin+Alt+M"

  # Close focused window.
  - command: "close"
    binding: "LWin+Alt+Shift+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "LWin+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "LWin+Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec wt /focus"
    binding: "LWin+Alt+Enter"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "LWin+Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "LWin+Alt+T"
  - command: "focus workspace prev"
    binding: "LWin+Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "LWin+Alt+1"
  - command: "focus workspace 2"
    binding: "LWin+Alt+2"
  - command: "focus workspace 3"
    binding: "LWin+Alt+3"
  - command: "focus workspace 4"
    binding: "LWin+Alt+4"
  - command: "focus workspace 5"
    binding: "LWin+Alt+5"
  - command: "focus workspace 6"
    binding: "LWin+Alt+6"
  - command: "focus workspace 7"
    binding: "LWin+Alt+7"
  - command: "focus workspace 8"
    binding: "LWin+Alt+8"
  - command: "focus workspace 9"
    binding: "LWin+Alt+9"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "LWin+Alt+A"
  - command: "move workspace right"
    binding: "LWin+Alt+F"
  - command: "move workspace up"
    binding: "LWin+Alt+D"
  - command: "move workspace down"
    binding: "LWin+Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "LWin+Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "LWin+Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "LWin+Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "LWin+Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "LWin+Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "LWin+Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "LWin+Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "LWin+Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["LWin+Alt+Shift+9"]
```
