### ISSUE TITLE
[Feature Request] Reorder the workspace index, after close the workspace

### ISSUE THREAD

**Issue by QPH-Coding** [glzr-io/glazewm#492]
- Description: 
Now, when the middle workspace is closed without any window, it automatically closes and removes the workspace. However, it does not reorder the indexes of the workspaces. I would like the indexes of the workspaces to be reorganized after removing the middle workspace.

- Feature Details:
  - Now: `1, 2, 3, 4, 5 -> 1, 2, 4, 5 (after close any windows in workspace[3])`
  - Expect: `1, 2, 3, 4, 5 -> 1, 2, 3, 4 (after close any windows in workspace[3])`
  - Config: 
  ```yaml
  general:
    ...
    # when close a workspace, reorder workspace indexes(default: true)
    # eg. 1, 2, 3, 4, 5 -> 1, 2, 3, 4 (after close any windows in workspace[3])
    auto_reorder_workspace: true
  ```
