### ISSUE TITLE
Music Component not showing

### ISSUE THREAD

**Issue by cdurbin909** [glzr-io/glazewm#512]
## Issue
When adding the music component to `components_center` nothing shows up on reload.

Currently on **Windows 11**, which could be the cause of the problem.

Code in my config:
```yaml
components_center:
    - type: "music"
      label_not_playing: ""
      label_paused: "{song_title} - {artist_name}"
      label_playing: "{song_title} - {artist_name} ▶"
      max_title_length: 20
      max_artist_length: 20
```
