### ISSUE TITLE
Set of Workspaces Per Monitor

### ISSUE THREAD

**Issue by GhoulBoii** [glzr-io/glazewm#582]
I would like an option to use the workspaces feature like it is used in suckless dwm. 

In dwm, you can assign a set of workspaces per monitor and you can switch your focus between the monitors to access those workspaces. For example, monitor 1 can have 1-5 workspaces which you can access with super+{1,5} and then you can switch to monitor 2 with super+. to the second monitor to access another set of 1-5 workspaces.

I have searched the configs and couldn't find anything to get this behaviour.

**Comment by GhoulBoii** [comment]
Thanks for the response. I did go through that config but that didn't suit what I wanted. I want to have 1-5 workspaces be activated by 1-5 keys on both of my monitors. For example, on monitor 1, I want 1-5 to activate 1-5 workspaces and if i switch to the second monitor, I want the same to happen. Switching between the monitors should happen with another key.

**Comment by FrostyNick** [comment]
This might be what you're looking for (from auto-generated config file):

```yaml
keybindings:
  # ...
  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+A"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"
```

Not to be mistaken with `move to workspace` which switches workspaces instead of monitor if I'm not mistaken.

**Comment by GhoulBoii** [comment]
> This might be what you're looking for (from auto-generated config file):
> 
> ```yaml
> keybindings:
>   # ...
>   # Move focused workspace to a monitor in a given direction.
>   - command: "move workspace left"
>     binding: "Alt+A"
>   - command: "move workspace right"
>     binding: "Alt+F"
>   - command: "move workspace up"
>     binding: "Alt+D"
>   - command: "move workspace down"
>     binding: "Alt+S"
> ```
> 
> Not to be mistaken with `move to workspace` which switches workspaces instead of monitor if I'm not mistaken.

This seems like a good solution but the problem is that if I have multiple windows then the workspace containing the windows get transferred over. This behaviour is i3wm like. I would rather have more importance given to the windows than the workspaces when working in a multi monitor setup.

**Comment by mischavandenburg** [comment]
> This might be what you're looking for (from auto-generated config file):
> 
> ```yaml
> keybindings:
>   # ...
>   # Move focused workspace to a monitor in a given direction.
>   - command: "move workspace left"
>     binding: "Alt+A"
>   - command: "move workspace right"
>     binding: "Alt+F"
>   - command: "move workspace up"
>     binding: "Alt+D"
>   - command: "move workspace down"
>     binding: "Alt+S"
> ```
> 
> Not to be mistaken with `move to workspace` which switches workspaces instead of monitor if I'm not mistaken.

Thank you this is exactly what I needed

**Comment by erlenmeyer316** [comment]
GlazeWM is great by the way. It's made moving to windows bearable for me. I tried another (komorebi and whkd) just because it looked  looked similar to yabai and skhd, but GlazeWM is superior by far imo. Looking forward to to new Rust rewrite.   

That said, this feature would be a massive improvement my workflow. 

1 workspace config with up to 10 (0-9) workspaces, which is replicated on each monitor and the keybinds for focusing workspaces would work on the currently focused monitor. Same idea for moving focused windows to a workspace. It only happens on the focused monitor. 

It does create a new case where keybinds and functionality would be needed to move focused windows to a desired monitor or focus a specific monitor. I think moving windows to the first workspace on the monitor would be acceptable and simplify keybinds. Once a window is in the first workspace on a specific monitor the standard keybinds and existing functionality could be used to change it work a different workspace on that monitor. 

## Example: 

**Assumptions**: 3 monitors. Each monitor has 10 workspaces (0-9). 

### Focusing workspaces on a monitor
- If **monitor 1** is focused and I press _Alt+3_, then **workspace 3** _on_ **monitor 1** gets focus. 
- If **monitor 2** is focused and I press _Alt+4_, then **workspace 4** _on_ **monitor 2** gets focus.
- If **monitor 3** is focused and I press _Alt+9_, then **workspace 9** _on_ **monitor 3** gets focus.

### Moving focused windows between workspace on monitor
- If a window in **workspace 3** _on_ **monitor 1** is focused and I press _Alt+Shift+7_, then the focused window would get move to **workspace 7** _on_ **monitor 1**
- If a window in **workspace 4** _on_ **monitor 2** is focused and I press _Alt+Shift+1_, then the focused window would get move to **workspace 1** _on_ **monitor 2**
- If a window in **workspace 9** _on_ **monitor 3** is focused and I press _Alt+Shift+3_, the focused window would get move to **workspace 3** _on_ **monitor 3**

### Moving focused windows between monitors
- If a window _in_ **workspace 7** _on_ **monitor 1** is focused and I press _Alt+Ctl+Shift+3_, the focused window would get moved _to_ **workspace 1** _on_ **monitor 3**
- If a window _in_ **workspace 1** _on_ **monitor 2** is focused and I press _Alt+Ctl+Shift+1_, the focused window would get moved _to_ **workspace 1** _on_ **monitor 1**
- If a window _in_ **workspace 3** _on_ **monitor 3** is focused and I press _Alt+Ctl+Shift+2_, the focused window would get moved _to_ **workspace 1** _on_ **monitor 2**

### Focusing monitors
- If a window _on_ **monitor 1** is focused and I press _Alt+Ctl+3_, the focus would be change to **window 1**, _in_ **workspace 1**, _on_ **monitor 3**
- If a window _on_ **monitor 2** is focused and I press _Alt+Ctl+1_, the focus would be change to **window 1**, _in_ **workspace 1**, _on_ **monitor 1**
- If a window _on_ **monitor 3** is focused and I press _Alt+Ctl+2_, the focus would be change to **window 1**, _in_ **workspace 1**, _on_ **monitor 2**


Hopefully that make sense.

**Comment by sam-lex** [comment]
> ### Focusing workspaces on a monitor
> * If **monitor 1** is focused and I press _Alt+3_, then **workspace 3** _on_ **monitor 1** gets focus.
> * If **monitor 2** is focused and I press _Alt+4_, then **workspace 4** _on_ **monitor 2** gets focus.
> * If **monitor 3** is focused and I press _Alt+9_, then **workspace 9** _on_ **monitor 3** gets focus.

Check out my script NodeJS.
https://gist.github.com/sam-lex/2f854cacff3efe94abbc232e84d3ce10
Does exactly that. You'll need to have your config.yaml set up to use the script too.

> ### Moving focused windows between workspace on monitor
> * If a window in **workspace 3** _on_ **monitor 1** is focused and I press _Alt+Shift+7_, then the focused window would get move to **workspace 7** _on_ **monitor 1**
> * If a window in **workspace 4** _on_ **monitor 2** is focused and I press _Alt+Shift+1_, then the focused window would get move to **workspace 1** _on_ **monitor 2**
> * If a window in **workspace 9** _on_ **monitor 3** is focused and I press _Alt+Shift+3_, the focused window would get move to **workspace 3** _on_ **monitor 3**

Same, copy the same script above, and change this on line 21 [customFocusWorkspace.ts](https://gist.github.com/sam-lex/2f854cacff3efe94abbc232e84d3ce10#file-customfocusworkspace-ts)
From: ```await client.runCommand(`focus --workspace ${args[index]}`);```
to: ```await client.runCommand(`move --workspace ${args[index]}`);```

> ### Moving focused windows between monitors
> ### Focusing monitors

For moving and focusing between monitors, I just Move/Focus left/right.
But you can totally make your own custom scripts.

**Comment by Weckmuller** [comment]
> **Assumptions**: 3 monitors. Each monitor has 10 workspaces (0-9).
> ### Focusing workspaces on a monitor
> 
>     * If **monitor 1** is focused and I press _Alt+3_, then **workspace 3** _on_ **monitor 1** gets focus.
> 
>     * If **monitor 2** is focused and I press _Alt+4_, then **workspace 4** _on_ **monitor 2** gets focus.
> 
>     * If **monitor 3** is focused and I press _Alt+9_, then **workspace 9** _on_ **monitor 3** gets focus.

I would also love for that feature to be natively supported in GlazeWM.

I'm coming from komorebic and this is the ONE thing I'm missing.

**Comment by dotaxis** [comment]
Really interested in this as well since I use 3 monitors, and splitting 10 workspaces across 3 screens is not ideal for me.

The script posted above does not seem to work for me, unfortunately.

Edit: I got the script working. The gist did not include the helper.functions.ts but luckily it existed in another gist by @sam-lex. I was not aware that the TS files needed to be built using npm after installing the `ws` and `glazewm` packages as well but now that that is all done and compiled it is working great.

Would still love to see native support for this in the future.

**Comment by jmarti326** [comment]
> Really interested in this as well since I use 3 monitors, and splitting 10 workspaces across 3 screens is not ideal for me.
> 
> The script posted above does not seem to work for me, unfortunately.
> 
> Edit: I got the script working. The gist did not include the helper.functions.ts but luckily it existed in another gist by [@sam-lex](https://github.com/sam-lex). I was not aware that the TS files needed to be built using npm after installing the `ws` and `glazewm` packages as well but now that that is all done and compiled it is working great.
> 
> Would still love to see native support for this in the future.

Interested in understanding a bit more how you did it @dotaxis 

I am looking for a similar solutions to yours.

**Comment by FelixSchausberger** [comment]
> Interested in understanding a bit more how you did it [@dotaxis](https://github.com/dotaxis)
> 
> I am looking for a similar solutions to yours.

Disclaimer: I am a Linux user and have little experience with Win 11 and Typescript, but I managed it as follows:

1. Copy [customFocusWorkspace.ts](https://gist.github.com/sam-lex/2f854cacff3efe94abbc232e84d3ce10#file-customfocusworkspace-ts) and [helpers.functions.ts](https://gist.github.com/sam-lex/dbdfab44489dacab656aed94f0499d3b#file-helpers-functions-ts) to `C:\Users\%userprofile%\.glzr\glazewm\scripts`.
2. Install npm: [How to Install npm on Windows 11](https://www.supportyourtech.com/tech/how-to-install-npm-on-windows-11-a-step-by-step-guide-for-beginners/)
3. Set up a typescript project in  `C:\Users\%userprofile%\.glzr\glazewm\scripts`: [How to Setup a TypeScript Project?](https://www.geeksforgeeks.org/typescript/how-to-setup-a-typescript-project/)
4. Install ws and glazewm with npm: `npm install ws glazewm`.
5. Add a build command to your `C:\Users\%userprofile%\.glzr\glazewm\scripts\package.json`:
```
"scripts": {
    "build": "tsc --build",
  },
```
6. Build the project with `npm run-script build`.
7. Adapt your `C:\Users\%userprofile%\.glzr\glazewm\config.yaml` to something like [this](https://gist.github.com/sam-lex/2f854cacff3efe94abbc232e84d3ce10#file-config-yaml).
8. Reload GlazeWM with `Alt+Shift+R`.

**Comment by sam-lex** [comment]
I have since moved to arch with i3wm about 1-2 months ago. I use typescript on a daily basis, but tbh I still don't really know how to "set it up", specially if I'm making a small little project with multiple files and need a `tsconfig.json`, what kind of modules to use always annoys me. Now I usually just ask gemini to help me set up, I follow the instructions (not really, just copy/paste) until I can run typescript easily.
I had quite a few scripts for glazewm, which is why I had a `helpers.functions.ts` which has some badly named functions in it for other stuff..
But the script for `customFocusWorkspace.ts` is rather simple, only uses a `promiseTimeout` function, normally when share the Github Gist, I would've just copied the function into a single file, instead of it requiring multiple files.. But looks like I forgot to do it.. sorry about that 😶 
This would've been the only file needed, if I didn't forgot to include the function in it
```typescript
// File: customFocusWorkspace.ts
/**
 * Focuses workspace based on current monitor
 * Required Argument: workspaceName_1 workspaceName_2 .. workspaceName_N
 */
import { WmClient } from 'glazewm';

const args = process.argv.slice(2);
if (!args.length) {
  console.log('No arguments provided');
  process.exit(0);
}

const client = new WmClient();
client.onConnect(async () => {
  const { monitors } = await client.queryMonitors();
  const index = monitors.findIndex(m => m.hasFocus);
  if (index < 0 || index >= args.length)
    console.warn(`Index: [${index}] out of args.length(${args.length}) bounds.`);
  else // Valid
    await client.runCommand(`focus --workspace ${args[index]}`);

  await promiseTimeout(1000);
  process.exit(0);
});

// Helper Functions ----
function promiseTimeout(ms: number): Promise<void> {
  return new Promise<void>(resolve => setTimeout(resolve, ms));
}
```
The instructions provided by @FelixSchausberger is perfect! I also completely forgot about `npm install ws glazewm`

**Comment by FelixSchausberger** [comment]
I updated the script so you can now move focused windows between workspaces depending on the active monitor:
```
// File: workspaceAction.ts
/**
 * Performs workspace action (focus/move) based on current monitor
 * Required Arguments: <action> <workspace1> [workspace2] [workspace3] ...
 * Actions: focus, move
 *
 * Example:
 *   node workspaceAction.js focus a1 b1 c1
 *   node workspaceAction.js move a1 b1 c1
 *
 * Workspaces should be provided in the same order as monitors.
 * For example, if you have 3 monitors and want to map them to a1, b1, c1:
 *   - "focus a1 b1 c1" will focus the correct workspace depending on which monitor is active
 *   - "move a1 b1 c1" will move the focused window to the corresponding workspace
 */
import { WmClient } from 'glazewm';

const args = process.argv.slice(2);
if (args.length < 2) {
    console.log('Usage: node workspaceAction.js <focus|move> <workspace1> [workspace2] ...');
    process.exit(0);
}

const [action, ...workspaces] = args;
if (!action || !['focus', 'move'].includes(action)) {
    console.error('Invalid action. Use "focus" or "move".');
    process.exit(1);
}

const client = new WmClient();
client.onConnect(async () => {
    const { monitors } = await client.queryMonitors();
    const index = monitors.findIndex(m => m.hasFocus);

    if (index < 0 || index >= workspaces.length) {
        console.warn(`Index: [${index}] out of workspaces.length(${workspaces.length}) bounds.`);
    } else {
        await client.runCommand(`${action} --workspace ${workspaces[index]}`);
        if (action === 'move') {
            await client.runCommand(`focus --workspace ${workspaces[index]}`);
        }
    }

    process.exit(0);
});
```

## Usage examples

Workspaces are passed in the same order as monitors (e.g. a1 b1 c1 for monitors 1, 2, 3).

### Focus a workspace:
```
- commands: ['shell-exec --hide-window node "%userprofile%/.glzr/glazewm/scripts/workspaceAction.js" focus a1 b1 c1']
  bindings: ['alt+1']
```

### Move a window to a workspace:
```
- commands: ['shell-exec --hide-window node "%userprofile%/.glzr/glazewm/scripts/workspaceAction.js" move a1 b1 c1']
  bindings: ['alt+shift+1']
```

**Comment by rpop0** [comment]
Hello. While having scripts is a okay workaround, this is not ideal. The ability to have workspace-related keybinds only affect the current monitor would be amazing.

**Comment by ahmadinne** [comment]
this is how i do it:

alt+number for first monitor
win+number for second monitor

```yaml
general:
  cursor_jump:
    enabled: true # cursor follow where monitor focused
    trigger: 'monitor_focus' # monitor_focus / window_focus

workspaces:
  # Monitor 0 / First Monitor
  - name: 'a1'
    display_name: '1'
    bind_to_monitor: 0
  - name: 'a2'
    display_name: '2'
    bind_to_monitor: 0
  - name: 'a3'
    display_name: '3'
    bind_to_monitor: 0
  - name: 'a4'
    display_name: '4'
    bind_to_monitor: 0
  - name: 'a5'
    display_name: '5'
    bind_to_monitor: 0
  - name: 'a6'
    display_name: '6'
    bind_to_monitor: 0
  - name: 'a7'
    display_name: '7'
    bind_to_monitor: 0
  - name: 'a8'
    display_name: '8'
    bind_to_monitor: 0
  - name: 'a9'
    display_name: '9'
    bind_to_monitor: 0
  - name: 'a10'
    display_name: '10'
    bind_to_monitor: 0

  # Monitor 1 / Second Monitor
  - name: 'b1'
    display_name: '1'
    bind_to_monitor: 1
  - name: 'b2'
    display_name: '2'
    bind_to_monitor: 1
  - name: 'b3'
    display_name: '3'
    bind_to_monitor: 1
  - name: 'b4'
    display_name: '4'
    bind_to_monitor: 1
  - name: 'b5'
    display_name: '5'
    bind_to_monitor: 1
  - name: 'b6'
    display_name: '6'
    bind_to_monitor: 1
  - name: 'b7'
    display_name: '7'
    bind_to_monitor: 1
  - name: 'b8'
    display_name: '8'
    bind_to_monitor: 1
  - name: 'b9'
    display_name: '9'
    bind_to_monitor: 1
  - name: 'b10'
    display_name: '10'
    bind_to_monitor: 1

keybindings:
  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace a1']
    bindings: ['alt+1']
  - commands: ['focus --workspace a2']
    bindings: ['alt+2']
  - commands: ['focus --workspace a3']
    bindings: ['alt+3']
  - commands: ['focus --workspace a4']
    bindings: ['alt+4']
  - commands: ['focus --workspace a5']
    bindings: ['alt+5']
  - commands: ['focus --workspace a6']
    bindings: ['alt+6']
  - commands: ['focus --workspace a7']
    bindings: ['alt+7']
  - commands: ['focus --workspace a8']
    bindings: ['alt+8']
  - commands: ['focus --workspace a9']
    bindings: ['alt+9']
  - commands: ['focus --workspace a10']
    bindings: ['alt+0']
  # Monitor 2
  - commands: ['focus --workspace b1']
    bindings: ['lwin+1']
  - commands: ['focus --workspace b2']
    bindings: ['lwin+2']
  - commands: ['focus --workspace b3']
    bindings: ['lwin+3']
  - commands: ['focus --workspace b4']
    bindings: ['lwin+4']
  - commands: ['focus --workspace b5']
    bindings: ['lwin+5']
  - commands: ['focus --workspace b6']
    bindings: ['lwin+6']
  - commands: ['focus --workspace b7']
    bindings: ['lwin+7']
  - commands: ['focus --workspace b8']
    bindings: ['lwin+8']
  - commands: ['focus --workspace b9']
    bindings: ['lwin+9']
  - commands: ['focus --workspace b10']
    bindings: ['lwin+0']
  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace a1', 'focus --workspace a1']
    bindings: ['alt+shift+1']                               
  - commands: ['move --workspace a2', 'focus --workspace a2']
    bindings: ['alt+shift+2']                               
  - commands: ['move --workspace a3', 'focus --workspace a3']
    bindings: ['alt+shift+3']                               
  - commands: ['move --workspace a4', 'focus --workspace a4']
    bindings: ['alt+shift+4']                               
  - commands: ['move --workspace a5', 'focus --workspace a5']
    bindings: ['alt+shift+5']                               
  - commands: ['move --workspace a6', 'focus --workspace a6']
    bindings: ['alt+shift+6']                               
  - commands: ['move --workspace a7', 'focus --workspace a7']
    bindings: ['alt+shift+7']                               
  - commands: ['move --workspace a8', 'focus --workspace a8']
    bindings: ['alt+shift+8']                               
  - commands: ['move --workspace a9', 'focus --workspace a9']
    bindings: ['alt+shift+9']
  - commands: ['move --workspace a10', 'focus --workspace a10']
    bindings: ['alt+shift+0']
  # Monitor 2
  - commands: ['move --workspace b1', 'focus --workspace b1']
    bindings: ['lwin+shift+1']                             
  - commands: ['move --workspace b2', 'focus --workspace b2']
    bindings: ['lwin+shift+2']                             
  - commands: ['move --workspace b3', 'focus --workspace b3']
    bindings: ['lwin+shift+3']                            
  - commands: ['move --workspace b4', 'focus --workspace b4']
    bindings: ['lwin+shift+4']                            
  - commands: ['move --workspace b5', 'focus --workspace b5']
    bindings: ['lwin+shift+5']                            
  - commands: ['move --workspace b6', 'focus --workspace b6']
    bindings: ['lwin+shift+6']                            
  - commands: ['move --workspace b7', 'focus --workspace b7']
    bindings: ['lwin+shift+7']                            
  - commands: ['move --workspace b8', 'focus --workspace b8']
    bindings: ['lwin+shift+8']                            
  - commands: ['move --workspace b9', 'focus --workspace b9']
    bindings: ['lwin+shift+9']
  - commands: ['move --workspace b10', 'focus --workspace b10']
    bindings: ['lwin+shift+0']
```
