### ISSUE TITLE
"move to workspace" doesn't work with keybinds using

### ISSUE THREAD

**Issue by EdualcLaiv** [glzr-io/glazewm#583]
## Description

When a binding involving a digit key on the numpad is set for the action to move the focused window to a workspace, it doesn't work.

## Version
GlazeWM : 2.1.1 installed via winget
Windows 11 22H2

## How to reproduce

Here's a snippet of my config file:

```yaml
  # Numpad bindings work here
  - command: "focus workspace 1"
    bindings: ["Alt+NumPad1", "Alt+1"]
  - command: "focus workspace 2"
    bindings: ["Alt+NumPad2", "Alt+2"]
  - command: "focus workspace 3"
    bindings: ["Alt+NumPad3", "Alt+3"]
  - command: "focus workspace 4"
    bindings: ["Alt+NumPad4", "Alt+4"]
  - command: "focus workspace 5"
    bindings: ["Alt+NumPad5", "Alt+5"]
  - command: "focus workspace 6"
    bindings: ["Alt+NumPad6", "Alt+6"]
  - command: "focus workspace 7"
    bindings: ["Alt+NumPad7", "Alt+7"]
  - command: "focus workspace 8"
    bindings: ["Alt+NumPad8", "Alt+8"]
  - command: "focus workspace 9"
    bindings: ["Alt+NumPad9", "Alt+9"]

  # Numpad bindings don't work here
  - commands: ["move to workspace 1", "focus workspace 1"]
    bindings: ["Alt+Shift+NumPad1", "Alt+Shift+1"]
  - commands: ["move to workspace 2", "focus workspace 2"]
    bindings: ["Alt+Shift+NumPad2", "Alt+Shift+2"]
  - commands: ["move to workspace 3", "focus workspace 3"]
    bindings: ["Alt+Shift+NumPad3", "Alt+Shift+3"]
  - commands: ["move to workspace 4", "focus workspace 4"]
    bindings: ["Alt+Shift+NumPad4", "Alt+Shift+4"]
  - commands: ["move to workspace 5", "focus workspace 5"]
    bindings: ["Alt+Shift+NumPad5", "Alt+Shift+5"]
  - commands: ["move to workspace 6", "focus workspace 6"]
    bindings: ["Alt+Shift+NumPad6", "Alt+Shift+6"]
  - commands: ["move to workspace 7", "focus workspace 7"]
    bindings: ["Alt+Shift+NumPad7", "Alt+Shift+7"]
  - commands: ["move to workspace 8", "focus workspace 8"]
    bindings: ["Alt+Shift+NumPad8", "Alt+Shift+8"]
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+NumPad9", "Alt+Shift+9"]
```

## Expected behaviour

`Alt+Shift+NumPad1` and `Alt+Shift+1` should both work, but only `Alt+Shift+1` does.
`Alt+Shift+NumPad1` seems to do nothing.

It's the same for every digit.

The odd thing is that digits on the numpad do work when they are bind to just change focus.

## Notes

I don't think it does matter, but it was tested with an AZERTY keyboard (french variant of QWERTY).

Usually when there is issues with shortcuts on an AZERTY, it affect the digits on the top row (since you need to press shift to type them), not on the numpad.
