### ISSUE TITLE
[bug/question] keybinds conflict with Windows Terminal

### ISSUE THREAD

**Issue by k4lizen** [glzr-io/glazewm#588]
Namely, the Windows Terminal uses alt+arrows to switch between panes, and glazewm uses alt+arrows to switch between windows. Is there an intended/recommended resolution for this keybind conflict?

**Comment by catvox** [comment]
i think you can us windows powertoys to change keybind. it is usefull!

**Comment by Bublade** [comment]
I've remvoed the arrow keys from the bindings and use the hjkl bindings instead
You can change https://github.com/glzr-io/GlazeWM/blob/main/GlazeWM.App/Resources/sample-config.yaml#L127-L136
Into
```yml
keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]
```

If you are windows powertoys there will be more conflicts
alt+space (focus floating/tiling mode)
alt+shift+space (toggle floating/tiling mode)

I've moved those to alt+z and alt+shift+z
