### ISSUE TITLE
[v2.1.1] Music widget doesn't escape special characters in song title or artist

### ISSUE THREAD

**Issue by BartHageman** [glzr-io/glazewm#639]
The music widget doesn't seem to escape special characters like & and * in the song title or artist properly, which breaks the widget until a different song is played without special characters.

Below an image of the widget being broken by an ampersand in the artist name:
![image](https://github.com/user-attachments/assets/90635e72-23df-4644-af38-b361e5e4c9fc)
And what it looks like normally:
![image](https://github.com/user-attachments/assets/421c3ae1-7644-4ff2-9b4b-3ac309417b31)
My config for the widget:
```YAML
    - type: "music"
      label_not_playing: ""
      label_paused: "<attr ff='Spotify Mix Bold'>Paused:</attr>   <attr ff='Iosevka Nerd Font' fg='#ccc' fs='16px'>    </attr>  <attr fg='#ccc' ff='Spotify Mix Regular'>{song_title}</attr>  ·  <attr ff='Spotify Mix Regular' fg='#ccc'>{artist_name}</attr>"
      label_playing: "<attr ff='Spotify Mix Bold'>Now Playing:</attr>   <attr ff='Iosevka Nerd Font' fg='#1fdf64' fs='16px'>    </attr>  <attr fg='#1fdf64' ff='Spotify Mix Regular'>{song_title}</attr>  ·  <attr ff='Spotify Mix Regular' fg='#ccc'>{artist_name}</attr>"
      max_title_length: 20
      max_artist_length: 20
      margin: "0 0px"
      padding: "0 8px"

```
