### ISSUE TITLE
[v3.1.0] Fullscreen window is not respected in Dual monitor setup.

### ISSUE THREAD

**Issue by dipta10** [glzr-io/glazewm#644]
### Steps to reproduce

1. Go to workspace on the left monitor
2. Make a window full screen on the left monitor
3. Go back to workspace on the right monitor
4. Go back to workspace on the left monitor. The Fullscreen window on the left monitor is not selected.

A video is attached demonstrating the issue.

https://github.com/user-attachments/assets/a60f13e5-83ce-4bd8-b4f5-f984fbee4e1f

### Workaround

Current behavior is focus --direction <DIRECTION> will look for a tiling window if the focused window is also a tiling
We could do something like this in the config.
```
keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left', 'wm-cycle-focus']
    bindings: ["RMenu+A", "RMenu+H"]
```

But this may have side effect if we have a floating window in the mix.
