### ISSUE TITLE
Unable to reload the config (v3.1.0)

### ISSUE THREAD

**Issue by AfzGit** [glzr-io/glazewm#646]
The command is executed by it does not reload the config

The command for reload passes as indicated in the log:
```
2024-08-06T12:42:56.905971Z INFO glazewm::common::commands::reload_config: Config reloaded.
2024-08-06T12:42:56.918321Z INFO glazewm: Received WM event: UserConfigChanged { config_path: "C:\\Users\\user\\.glzr/glazewm/config.yaml", config_string: "general:\n    # Commands to run when the WM has started (e.g. to run a script or launch
...
```

>Windows 11 23H2

**Comment by AmineDjeghri** [comment]
@AfzGit  I have this issue #649 
I think they might be related

**Comment by AfzGit** [comment]
Ok i figured out what was the problem.
GlazeWM's Reload will only reload GlazeWM config and not Zebar config. So for any changes in Zebar's config, you need to restart Zebar manually.


A temporary fix:
```
    # Re-evaluate configuration file.
    - commands: ["wm-reload-config", 'shell-exec taskkill /IM "zebar.exe" /F', "shell-exec %userprofile%/.glzr/zebar/start.bat",]
      bindings: ["alt+shift+r"]
```
Now, upon reload, Zebar closes and relaunches, making the config of Zebar reload.

---
Can we add support to also reload Zebar from the same shortcut `alt+shift+r`?

**Comment by raphtlw** [comment]
The proposed solution above no longer works properly due to Zebar sometimes starting before the kill command is run, as both of the commands are run asynchronously.

Updated fix:

```yaml
# Re-evaluate configuration file.
  - commands: ['wm-reload-config', 'shell-exec --hide-window powershell -command "taskkill /IM zebar.exe /F; zebar"']
    bindings: ['lwin+shift+r']
```

**Comment by AfzGit** [comment]
@raphtlw Thanks for the solution. I thought i was the only one for whom it wasn't working so i didn't bother reporting it further. Your solution works perfectly fine. The same solution but with the new `general.reload` syntax:

```yaml
general:    
  config_reload_commands: ['shell-exec --hide-window powershell -command "taskkill /IM zebar.exe /F; zebar"']

keybindings:
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

```
