### ISSUE TITLE
Disable border highlight for the focused window on a specific window.

### ISSUE THREAD

**Issue by a0w89fwa0f** [glzr-io/glazewm#653]
Is it possible to disable the focused border highlight for a specific window.

I use an extension for Visual Studio Code which makes the window transparent and the border highlight color fills the entire window making it unusable: https://github.com/illixion/vscode-vibrancy-continued

Thanks

**Comment by lars-berger** [comment]
We could add a `match` option like like with window rules, e.g.
```yaml
window_effects:
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
      match:
        - window_process: { equals: 'Code' }
```

**Comment by JonasWischeropp** [comment]
The current version is now fully functional and is using `window_effects`.
Furthermore I have added the ability to change the corner style of windows.

```yaml
focused_window:
  hide_title_bar:
    enabled: true
  corner:
    enabled: true
    # Allowed values: 'windows_default', 'square', 'round', 'small_round'
    style: 'square'
```

But I have noticed that removing the title bar of some windows can cause problems, e.g:
- notepad: visuals of the title bar are wrong
- windows file explorer: tabs in the title bar no longer fully work

Therefore it would be nice to have the ability to `match` like with `window_rules` (like discussed in #653).

But I think it could be beneficial to use `window_rules` instead of `window_effects`.
This would require the introduction of `WindowRuleEvent::Unfocus`.
For example instead of using:
```yaml
window_effects:
  focused_window:
    border:
      enabled: true
      color: '#8dbcff'
    hide_title_bar:
      enabled: false

  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: true
```
One could use:
```yaml
window_rules:
  - commands: ['set-title-bar-visibility false', 'set-border-color #8dbcf']
  # (set-border-color would need to be implemented)
    on: 'focus'
    run_once: false
    match:
      - window_class: { equals: 'example' }

  - commands: ['set-title-bar-visibility true', 'set-border-color #a1a1a1']
    on: 'unfocus'
    run_once: false
    match:
      - window_class: { equals: 'example' }
```
(Could be made cleaner by making `match` optional and matching everything when it is not provided.)

I think this system would be more extendable.
It would be easier to introduce new rules what effects should be applied when.
Because it allows to change effects not only when the focus changes but also on other `WindowRuleEvent`s.
Currently there are only three but others could be exposed in the future.
For example with a `WindowRuleEvent` like `BecameFloating` one could have round corners in floating mode and square corners in tiling mode.
This would probably also require new `MatchType`s but what I am trying to say is that I think that using `window_rules` would be more flexible in the future.


What do you think?
