### ISSUE TITLE
[Feature Request] Make Nerd Font icons available offline instead of fetching them. (v3.1.0)

### ISSUE THREAD

**Issue by AfzGit** [glzr-io/glazewm#658]
There are many problems that occur with an online approach:

**Problem Case 1:** You are outside without an internet connection, GlazeWM + Zebar will not load it's icons
**Problem Case 2:** Your system is slow to connect to Wi-Fi, GlazeWM launches at startup without Wi-Fi, so no icons are fetched.
**Problem Case 3:** Your Wi-Fi is slow/unresponsive, leaving you with no icons in Zebar (Happens a lot with me)
**Problem Case 4:** Site is unresponsive
**Problem Case 5:** File is moved/removed from Nerdfonts site
**Problem Case 6:** File is updated and class names can change, making previous use of classes in Zebar do nothing

Consider adding `webfont.css` file (600kb size) to the project for offline use to solve all the problems above. Offline use does not seem to be breaking any licenses.

---
Code to change:
```yaml
# Consider fetching this offline
window/bar:
    global_styles: |
        @import "https://www.nerdfonts.com/assets/css/webfont.css";
```
---
- No icons Without Wi-Fi:
  - ![image](https://github.com/user-attachments/assets/cb69be06-980a-4ea8-bc71-a04dc06ee99e)
- With Wi-Fi:
  - ![image](https://github.com/user-attachments/assets/1a2c345b-6031-412b-9c54-97f0e6e46e94)
