### ISSUE TITLE
floating windows are centered by default disable

### ISSUE THREAD

**Issue by xxmlud** [glzr-io/glazewm#668]
Hello,

I am using glazewm on Window 10.
I can't find the option to disable the option to have a window appear in the center by default when I start a window.

My configuration is as follows, but always when I open a window it starts in the center. 
I would like the behavior to be like the preview in the README.md, that the windows start to the right/left of the monitor.

```
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: false

``` 

Thank you

**Comment by lars-berger** [comment]
Was able to reproduce this

**Comment by yutotakano** [comment]
On top of floating windows starting centered, my windows sometimes suddenly become centered after launch too. I could be calculating something with the calculator app or writing in notepad.exe (both floating) and they'd suddenly be moved to the center of the monitor. It is very sporadic and frustratingly random, so much that I thought it might be a OOM or CPU exhaustion issue that causes GlazeWM to maybe restart, but this does not appear to be the case. So I have no idea.

The following is my relevant portion of the config. I don't have any keybindings to make a window centered either, so there's no accidental presses of something.

```
window_behavior:
  initial_state: 'floating'

  state_defaults:
    floating:
      centered: false
```
