### ISSUE TITLE
[Bug] failed to parse 'outer_gap' config

### ISSUE THREAD

**Issue by Jaehaks** [glzr-io/glazewm#670]
### Describe the bug

When I start glazewm in terminal , 
Encountered a problem is invoked

The message is 
>'Failed to pane user config. Invalid value at property. $.gaps.outer_gap'

I use default config supported in this repo. 
What i misunderstand?

**Comment by lars-berger** [comment]
Can you share your gaps config that's causing the error? also what version are you running?

**Comment by Jaehaks** [comment]
@lars-berger 

I installed the glazewm using `scoop`. It's version is 2.1.1
I called glazewm with `--config= ` to specify configuration file. 
The configuration file that I'm using is [default config](https://github.com/glzr-io/glazewm/blob/main/resources/assets/sample-config.yaml)

1) I erase `startup_commands`.
2) After I delete sublist of `outer_gap` and put '20px' next to `outer_gap`, 
   the error message is gone
    ```yaml
    gaps:
      inner_gap: '20px'
      outer_gap: '20px'
        # top: '60px'
        # right: '20px'
        # bottom: '20px'
        # left: '20px'
    ```
3) The next error is Unknown key 'alt'
![image](https://github.com/user-attachments/assets/2ae6f1a9-852e-4f45-9dfc-f928c9a1cf1e)

What i'm missing about configuration?
