### ISSUE TITLE
[Feature Request] Option to automatically enable binding mode depending on focused window

### ISSUE THREAD

**Issue by lars-berger** [glzr-io/glazewm#675]
### Describe the problem/motivation

Allow for keybindings to change depending on the focused application

### Describe the solution you'd like

**Proposed config:**

A new `match_enabled` option like this for binding modes
```yaml
binding_modes:
  - name: 'discord'
    # Automatically enable if the condition matches. And automatically disable when no longer true.
    match_enabled:
      # Possible match options: `focused_window_process`, `focused_window_class`, and `focused_window_title`
      - focused_window_process: { equals: 'discord' }
    keybindings:
      - commands: ['...']
        bindings: ['...']
```
