### ISSUE TITLE
[Bug] command to move window to a specific workspace not working

### ISSUE THREAD

**Issue by rottakore** [glzr-io/glazewm#694]
### Describe the bug

The following code:
```
window_rules:
  - commands: ['move --workspace 2']
    match:
      - window_process: { equals: '(software process name)' }
```
do not work.
I did some research in the problem and looks like it only affects some programs made with net framework (which the glazewm can't even put active or inactive borders in it, and windows 11 round corners don't work too), see an image below (can't show alot 'cause it's a program from my work):
![image](https://github.com/user-attachments/assets/d8bfc312-11a2-4f28-948a-50b7a7c42e49)

### Reproduction

Write the code in config.yaml and try it.

### Stack trace or error logs (if applicable)

```shell
no error.
```

### Version number

v3.1.1
