### ISSUE TITLE
[Bug] Tiling functionality stops working when gap is too small

### ISSUE THREAD

**Issue by nikitarevenco** [glzr-io/glazewm#697]
### Describe the bug

If the gap is too small none of the windows will tile and all new windows will be fullscreened

### Reproduction

Exact steps I'm following:

```yaml
gaps:
  inner_gap: "10px"
  outer_gap:
    top: "10px"
    right: "10px"
    bottom: "10px"
    left: "10px"
```

1. Set all gaps to `0px` as shown above
1. Open wezterm and chrome in non-fullscreen mode (https://github.com/glzr-io/glazewm/issues/682)
3. Run GlazeWM
4. The two windows tile normally
5. I send a window to another workspace
6. Now all tiling functionality is broken on all workspaces
7. All new windows will be fullscreened with no way to make them tile again
8. Kill WM and change config to this:

```yaml
gaps:
  inner_gap: "10px"
  outer_gap:
    top: "10px"
    right: "10px"
    bottom: "10px"
    left: "10px"
```

Repeat all above steps, but now everything works correctly

### Version number

v3.1.1
