### ISSUE TITLE
[Bug] Custom key bindings not working as expected

### ISSUE THREAD

**Issue by BubuDavid** [glzr-io/glazewm#714]
### Describe the bug

Hi there 👋, I understand commands can be "chained" for a certain key-binding, such as 
```yaml
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
```
And that works perfectly, but I am trying to bring a specific workspace from my monitor 0 to my monitor 1 (basically trying to not hurt my neck but still having 2 monitors), I tried with:

```yaml
  # Get the music workspace to screen 1
  - commands: ["focus --workspace 9", "move-workspace --direction right"]
    bindings: ["alt+shift+m"]
```

But does not work, I need to press the keys twice (do `alt+shift+m, alt+shift+m`) and that is kind of annoying (I mean it works I guess but why the first time this does not execute the move-workspace command?). Anyways, something similar happens when I tried to bind for a 'swap-window on two monitors' that you can see [here](https://github.com/glzr-io/glazewm/issues/380#issuecomment-2330641980), I am not sure if this is a bug or I just haven't read enough documentation so I am missing something...

### Reproduction

Install default and here is my config file (I haven't done anything else to it):
```yaml
general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands:
    [
      "shell-exec %userprofile%/.glzr/zebar/start.bat",
      "focus --workspace 9",
      "focus --workspace 0",
      "focus --workspace 1",
    ]

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

gaps:
  # Gap between adjacent windows.
  inner_gap: "5px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "45px"
    right: "10px"
    bottom: "10px"
    left: "10px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: "#a1a1a1"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
    display_name: "Terminal"
    bind_to_monitor: 1
  - name: "2"
    display_name: "Browser"
    bind_to_monitor: 1
  - name: "3"
    display_name: "Work"
    bind_to_monitor: 1
  - name: "4"
    bind_to_monitor: 1
  - name: "5"
    display_name: "WhatsApp"
    bind_to_monitor: 0
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
    display_name: "Music"
    bind_to_monitor: 0
    keep_alive: true
  - name: "0"
    display_name: "Extra"
    bind_to_monitor: 0
    keep_alive: true

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys.PowerAccent" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper*" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["alt+u"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+p"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+o"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+i"]

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["alt+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["alt+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ["shell-exec wt.exe"]
    bindings: ["alt+shift+enter"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["alt+s"]
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+a"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 0"]
    bindings: ["alt+0"]
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["alt+shift+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+shift+f"]
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+shift+d"]
  - commands: ["move-workspace --direction down"]
    bindings: ["alt+shift+s"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 0", "focus --workspace 0"]
    bindings: ["alt+shift+0"]
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]

  # Get the music workspace to screen 1
  - commands: ["focus --workspace 9", "move-workspace --direction right"]
    bindings: ["alt+shift+m"]

```

### Version number

v3.1.1

**Comment by jackkinsey** [comment]
Similar issue: I'm noticing that if I chain multiple `focus --workspace` and `move-workspace --direction` commands, the result is something like executing all the `focus` commands (so the last workspace focused in the chain is focused) and _then_ executing all the `move-workspace` commands. So take e.g., this binding:

```yaml
      - commands:
          - "focus --workspace 1"
          - "move-workspace --direction right"
          - "focus --workspace 2"
          - "move-workspace --direction left"
          - "focus --workspace 3"
          - "move-workspace --direction left"
        bindings: ["alt+m"]
```

Say the user has a three-monitor setup with this layout:

* Left
  * Workspace 1
  * Workspace 4
* Center
  * Workspace 2
  * Workspace 5
* Right
  * Workspace 3
  * Workspace 6

If the binding is executed, I would expect the result to be this: 

* Left
  * **Workspace 2**
  * Workspace 4
* Center
  * **Workspace 1**
  * **Workspace 3**
  * Workspace 5
* Right
  * Workspace 6

That is, each workspace is focused in turn and moved accordingly.

Instead, the result is this: 

* Left
  * Workspace 1
  * **Workspace 3**
  * Workspace 4
* Center
  * Workspace 2
  * Workspace 5
* Right
  * Workspace 6

That is, seemingly each workspace is focused in order, and then each move command is executed in order, so that workspace 3 (being the last focused workspace) is moved right (no-op, it's as far right as it can go) and then is moved left twice (ending up on the leftmost monitor).
