### ISSUE TITLE
[Bug] Windows don't obay window_rules and/or disappear and become background processes

### ISSUE THREAD

**Issue by Sh00Fly** [glzr-io/glazewm#718]
### Describe the bug

When I have two rules that are supposed to move either chrome or firefox to the same workspace things get weird.
Sometimes it works fine, sometimes a browser ends up on a random workspace, and sometimes a browser disappears and only can be found under background processes in task manager.
```
window_rules:
  - commands: ["move --workspace 04"]
    match:
      # Move browsers to workspace 04.
      - window_process: { regex: "chrome" }
      
  - commands: ["move --workspace 04"]
    match:
      # Move browsers to workspace 04.
      - window_process: { regex: "firefox" }
```
### Reproduction

Have two separate window rules move two programs to the same workspace.
Try to open and close the two programs repeatedly and observe windows misplaced and disappearing.

### Version number

v3.1.1
