### ISSUE TITLE
[Bug] some window rules don't work

### ISSUE THREAD

**Issue by perrylets** [glzr-io/glazewm#786]
### Describe the bug

My window rule that sets some windows to floating don't apply to the Flow launcher settings and Steam windows that aren't the main one (except for the news window), the rule that ignores the window applies correctly to Steam Big Picture mode, but leaves a small gap at the bottom of the screen. This worked perfectly fine before updating to 3.4.0

### Reproduction

```yaml
window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - commands: ["ignore"]
    match:
      - window_process: { equals: "steamwebhelper" }
        window_title: { regex: ".*Big Picture.*" }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: "steamwebhelper" }
        window_title: { regex: "(?!Steam).*" }

      - window_process: { equals: "Flow.Launcher" }
        window_title: { equals: "Settings" }

      - window_title: { equals: "Visual Studio Installer" }
```

### Version number

3.4.0
