### ISSUE TITLE
[Feature Request] Move focus window to another monitor

### ISSUE THREAD

**Issue by ragundo** [glzr-io/glazewm#791]
### Describe the problem/motivation

I've two monitors. 
If i move the focused window form monitor 1 to monitor 2 using Windows + CAPS + ARROW, 
glazewm don't tile the new moved window. It's only tiled as soon as I move the widow with the mouse

There's one option to movel ALL the windows to another monitor (in the currente workspace) but i want to move only one window and be correctly tiled

Terrific app by the way

Thanks 

### Describe the solution you'd like

Ideally , a bindable shortcut key in config.yaml

**Comment by flaschenpost** [comment]
Why could you not move the app to the workspace on the other monitor? If I have workspace 2 on the left monitor and workspace 7 on the right monitor, then Shift+Alt+7 moves it nicely to the other monitor and puts it right into its workspace.

**Comment by guangxu-li** [comment]
> Why could you not move the app to the workspace on the other monitor? If I have workspace 2 on the left monitor and workspace 7 on the right monitor, then Shift+Alt+7 moves it nicely to the other monitor and puts it right into its workspace.

save the mind to check what's the current workspace number on the left/down/up/right monitor before shooting the shortcuts

**Comment by sam-lex** [comment]
If you're familiar with node/typescript
You can modify this script to suit your needs:
I have 3 monitors, so I like having a "cycle", say I want to move a window from Monitor 3 to 1, instead of moving Left twice, I just move right once.
```typescript
/**
 * Move focused window to another monitor
 * Required Argument: 'left' | 'right'
 */
import { ContainerType, Monitor, WmClient } from 'glazewm';
import { promiseTimeout } from './helpers.functions';

type Direction = 'left' | 'right';

const [arg] = process.argv.slice(2);
if (arg !== 'left' && arg !== 'right') {
  console.error(`No valid argument provided: 'left' | 'right'`);
  process.exit(0);
}

const client = new WmClient();
client.onConnect(async () => {
  await run(arg);
  await promiseTimeout(1000);
  process.exit(0);
});

async function run(arg: Direction) {
  const { focused } = await client.queryFocused();
  if (focused.type !== ContainerType.WINDOW)
    return;

  const { monitors } = await client.queryMonitors();
  if (monitors.length === 1)
    return;

  // Make sure monitors are sorted Horizontally
  monitors.sort((a, b) => a.x - b.x);
  const focusedMonitor = monitors.find(m => m.hasFocus);

  const targetMonitor = getTargetSwapMonitor(focusedMonitor, monitors, arg);

  // Move to Target workspace
  const tWorkspace = targetMonitor.children.find(w => w.isDisplayed)!;
  await client.runCommand(`move --workspace ${tWorkspace.name}`, focused.id);
  await promiseTimeout(150);
  await client.runCommand(`focus --workspace ${tWorkspace.name}`);
}

function getTargetSwapMonitor(focusedMonitor: Monitor, monitors: Monitor[],
    direction: Direction): Monitor {
  const fIndex = monitors.indexOf(focusedMonitor);
  if (direction === 'left')
    return fIndex > 0 ? monitors[fIndex - 1] : monitors[monitors.length - 1];
    // return fIndex > 0 ? monitors[fIndex - 1] : undefined;
  else
    return fIndex < monitors.length - 1 ? monitors[fIndex + 1] : monitors[0];
    // return fIndex < monitors.length - 1 ? monitors[fIndex + 1] : undefined;
}
```
then, you'll bind it on the config.yaml after you've generated the `.js` file.
```yaml
  # Move Window to Monitor on the left
  - commands: ['shell-exec --hide-window node "C:\Users\Windows 10\.glzr\glazewm\scripts\dist\moveToMonitor.js" left']
    bindings: ['ctrl+alt+shift+h']

  # Move Window to Monitor on the right
  - commands: ['shell-exec --hide-window node "C:\Users\Windows 10\.glzr\glazewm\scripts\dist\moveToMonitor.js" right']
    bindings: ['ctrl+alt+shift+l']
```
