### ISSUE TITLE
[Bug] Shell-exec "custom terminal" create the default windows terminal application, and the "custom terminal"

### ISSUE THREAD

**Issue by PoutineSyropErable** [glzr-io/glazewm#795]
### Describe the bug

The shell exec command
like

`   -commands: ['shell-exec wezterm'] `
 `   bindings: ['alt+enter'] `

Here's a picture bellow. (Note the presence of another bug, Windows Snipping Tool doesn't work when GlazeWM is running), hence i need to stop it to take a screenshot. 
![GlazeWM](https://github.com/user-attachments/assets/a53e0d9c-de5f-43bf-9293-78c9bacb68d0)

### Reproduction

I have windows Terminal as my default terminal, but that's only for "Windows Like Environment". 
If I want to recreate my linux setup, Wezterm is my best way to do so.

I tried the same with firefox and luckily, such a thing didn't happen. 
So, it seems like it may be due to it being a terminal? 

### Stack trace or error logs (if applicable)

```shell
I do not know how to get my version.
```

### Version number

Latest version. Just downloaded it with winget at 8pm EST 2024-10-16

**Comment by PoutineSyropErable** [comment]
Here's the version:
/glazewm-v3.4.0.exe

**Comment by naufalauddin** [comment]
You could try https://github.com/glzr-io/glazewm/issues/452#issuecomment-2418302054

**Comment by lars-berger** [comment]
There's a new `--hide-window` flag that's been added for `shell-exec` which prevents the CMD window from opening when running scripts/shortcuts. It's available in the latest v3.6.0 release 👍 

So you can now either do:
```yaml
keybindings:
  - commands: ["shell-exec wezterm-gui"]
    bindings: ["alt+enter"]

  # or:
  - commands: ["shell-exec --hide-window wezterm"]
    bindings: ["alt+enter"]
```
