### ISSUE TITLE
[Feature Request] Disable gaps when only one window is open

### ISSUE THREAD

**Issue by St0wy** [glzr-io/glazewm#804]
### Describe the problem/motivation

Gaps look good when at least two windows are open, but where there's only one, it kinda feels like a waste of space of having them.

### Describe the solution you'd like

Adding a bool config `disable_gaps_when_single_window` that defaults to false in the `gaps` section.

**Comment by Dovias** [comment]
Im interested in doing a PR for this. I'm thinking to implement this in more customizable way by providing a way to set inner and outer gaps, based on the current window count like this:
```yaml
  # Gap between adjancent windows, based on the current window count in the workspace.
  inner_gap:
    - 2: 
      top: '20px'
      right: '20px'
      bottom: '20px'
      left: '20px'
    - 3:
      top: '10px'
      right: '10px'
      bottom: '10px'
      left: '10px'

  # Gap between windows and the screen edge, based on the window count in the workspace.
  outer_gap:
    - 1: 
      top: '0px'
      right: '0px'
      bottom: '0px'
      left: '0px'
    - 2:
      top: '20px'
      right: '20px'
      bottom: '20px'
      left: '20px'
```

If the window count is higher than the specified value in the configuration file, it will use the most highest value it is specified. In my opinion this approach is better since it allows to set outer_gap to 0 when window count is 1 whilst still allowing to make smaller gaps with higher window counts.
