### ISSUE TITLE
[Bug] Windows Terminal and Steam Big Picture leave a gap on the bottom of the screen when maximized

### ISSUE THREAD

**Issue by perrylets** [glzr-io/glazewm#814]
### Describe the bug

When steam big picture is opened or windows terminal is maximized, there's a 2 pixel gap between the bottom of the window and the bottom of the screen. 
![image](https://github.com/user-attachments/assets/b0b4f6a4-b833-46e2-98f7-1c6fd1de1843)

### Reproduction

```yaml
window_behavior:
  initial_state: "tiling"
  state_defaults:
    floating:
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: true
      shown_on_top: false

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "steamwebhelper" }
        window_title: { equals: "Big Picture" }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: "steamwebhelper" }
        window_title: { not_regex: "(Steam|Big Picture)" }

keybindings:
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+x"]
```

### Version number

3.5.0
