### ISSUE TITLE
[Bug] Notepad4's auto-completion can't work with glazewm

### ISSUE THREAD

**Issue by huainan1m** [glzr-io/glazewm#846]
### Describe the bug

I use [Notepad4](https://github.com/zufuliu/notepad4) to edit files.
Notepad4's auto-completion works like this:
![20241110192815](https://github.com/user-attachments/assets/41bdccb8-fdc0-40f0-9962-f8d7022c2ecc)
But when I opened glazewm, Notepad4's auto-completion list does not show up, it just causes the Notepad4 window to flicker, and even moves the focus to a floating window if there are other floating windows.
```
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'Notepad4' }
```
I tried `window_rules` to ignore Notepad4 process, but I prefer Notepad4 to work with glazewm, and Notepad4's auto-completion works fine.
How could I fix this? 

### Version number

3.5.0
