### ISSUE TITLE
[Feature Request] Transparency

### ISSUE THREAD

**Issue by skimask9** [glzr-io/glazewm#953]
### Describe the problem/motivation

The new transparent effect for focused and unfocused windows is really great, but I have some questions or suggestions. Toggling transparency on some windows would be helpful, especially if it's Chrome opened with YouTube on a second monitor :) Currently, the Ignore command leaves  the window transparent.

### Describe the solution you'd like

It would be nice to ignore that window and switch transparency off or create a completely new command to toggle transparency on unfocused/focused windows

**Comment by skimask9** [comment]
I have just realized that I can create a command  "set-transparency --opacity 0-100%" but it works perfectly in a focused window. I don't know how to do the same for a specific app that is unfocused :)

**Comment by solemnH** [comment]
![Image](https://github.com/user-attachments/assets/559d6157-22c3-4fad-9794-23fc0c9f29c3) adding it to window_rules should do the trick

**Comment by bkomadina** [comment]
> I have just realized that I can create a command "set-transparency --opacity 0-100%" but it works perfectly in a focused window. I don't know how to do the same for a specific app that is unfocused :)

could you please provide the code where you added `set-transparency --opacity 0-100%`?

I've tried the code below, move to workspace command moves Chrome to workspace 1 but the transparency doesn't change even when window_effects and focused_window transparency rules are just set to enabled without any further opacities set:
```
window_rules:
  - commands: ["move --workspace 1", "set-transparency --opacity 10%"]
    match:
      - window_process: { regex: "msedge|brave|chrome|firefox" }
```

**Comment by skimask9** [comment]
> > I have just realized that I can create a command "set-transparency --opacity 0-100%" but it works perfectly in a focused window. I don't know how to do the same for a specific app that is unfocused :)
> 
> could you please provide the code where you added `set-transparency --opacity 0-100%`?
> 
> I've tried the code below, move to workspace command moves Chrome to workspace 1 but the transparency doesn't change even when window_effects and focused_window transparency rules are just set to enabled without any further opacities set:
> 
> ```
> window_rules:
>   - commands: ["move --workspace 1", "set-transparency --opacity 10%"]
>     match:
>       - window_process: { regex: "msedge|brave|chrome|firefox" }
> ```

   - commands: ["set-transparency --opacity 100%"]
    bindings: ["alt+shift+c"]

**Comment by KhangHLe** [comment]
For anyone checking on this, I found a decent alternative solution building upon what the above poster said:

1. Disable transparency for focused and unfocused window

```yaml
window_effects:
  focused_window:
    transparency:
      enabled: false
  other_windows:
    transparency:
      enabled: false
```

2. Create window rule Set transparency in windows rules for ALL windows
```yaml
window_rules:
  - commands: ['set-transparency --opacity 98%']
    match:
      - window_process: { regex: '.*' }
```

3. Use the keybinding to disable transparency for any window you wish

```yaml
  # Toggle transparency
  - commands: ["set-transparency --opacity 100%"]
    bindings: ["alt+shift+c"]
```

The only caveat to this is that you cannot have automatic different opacity for focused vs unfocused windows

**Comment by theankou** [comment]
This way works too make sure that order correct: 

```
window_effects:
  focused_window:
    transparency:
      enabled: false
  other_windows:
    transparency:
      enabled: false
```

First this
```
window_rules:
  - commands: ['set-transparency --opacity 98%']
    match:
      - window_process: { regex: '.*' }
```      

And then this
```
  - commands: ["set-transparency --opacity 100%"]
    match:
      - window_process: { equals: "blender" }
      - window_process: { equals: 'toolbag' }
      - window_process: { equals: 'Adobe Substance 3D Painter' }
      - window_process: { equals: 'rizomuv' }
      - window_process: { equals: 'Photoshop' }   
```

Would be great to add this to description on main page for beginners, because currently for people like me (who can't code and don't understand how and where to place commands) it's hard to search for such things in issues category.
