### ISSUE TITLE
[Bug] Pause toggle not showing up in the Zebar

### ISSUE THREAD

**Issue by 4NXIE7Y** [glzr-io/glazewm#955]
### Describe the bug

Whenever enabling the `wm-toggle-pause` via `alt+shift+p` zebar is supposed to have a widget that shows that the binding state is currently paused.

![Image](https://github.com/user-attachments/assets/b841b2bd-d0e0-40a7-9afb-07dafc68863f)

Only way to get the `pause` widget is to use `wm-disable-binding-mode`.

### Stack trace or error logs (if applicable)

```shell

```

### Version number

3.8.1

**Comment by 4NXIE7Y** [comment]
Ok apparently `wm-disable-binding-mode` is not the same as `wm-toggle-pause` so yeah. This needs fixing...

**Comment by wondermike221** [comment]
Any updates on this?

I figure the root of the issue is that pause using wm-toggle-pause no longer puts pause on the binding modes array, it is just using the isPaused property instead.
Most zebar widget developers assume paused can be shown via the binding modes part of their widget but as we update to the new version of pause we no longer get the feedback in zebar that we are paused. 

Is pause no longer considered a binding mode?

**Comment by kyoryo** [comment]
This also happen in yasb, and I found that `wm-toggle-pause` is not same as `wm-enable/disable-binding-mode` (not properly marked pause as a binding mode).
The work around is use old method in config.yaml:
```yaml
binding_modes:
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']
keybindings:
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']
```
