### ISSUE TITLE
[Feature Request] Add CLI commands to enable/disable focus_follows_cursor and cursor_jump

### ISSUE THREAD

**Issue by clownroyal420** [glzr-io/glazewm#957]
### Describe the problem/motivation

In some cases, it might be useful for the user to suspend `focus_follows_cursor` and/or `cursor_jump`. This feature, if implemented, would be helpful for the following scenarios:
- Interacting with unmanaged or problematic windows.
- Using the mouse to interact with overlay elements such as the System Tray Overflow menu; or any UI element or window that disappears upon a loss of focus (such as Flow Launcher or Powertoys Run).

Example; in my AutoHotkey script I use with Komorebi, I suspend focus-follows-mouse any time ctrl is held down. When I would use Komorebi, this hotkey pretty much solved my woes with the above listed scenarios.

### Describe the solution you'd like

It looks like by default, it looks like GlazeWM refrains from focusing windows any time (1) either of the Right or Left mouse buttons is held down or (2) focus_follows_cursor config is set to false.

My preference would be a cli/glazewm.exe command to enable or disable (as opposed to toggle) a third conditional in line 16 of `packages/wm/src/events/handle_mouse_move.rs`. Or, if there would be a way to change the focus_follows_cursor config value that's loaded into glazewm; that would probably be the most intuitive barring any unexpected results from re-loading the config entirely.

### Alternatives considered

I've tried disabling focus_follows_cursor and using Windows's feature "Activate a window by hovering over it with the mouse" instead, as this setting (along with the built in time delay) can be set using the windows API and AutoHotkey. However, this results in an immediate loss of window focus any time windows are moved using `glazewm.exe command move`. I think if the cursor_jump feature were triggered upon a window move command as well as window_focus/workspace_focus, the built in Windows feature would behave just fine.

**Comment by dillacorn** [comment]
This gave me an idea... I have issues with AutoDesk software but really enjoy focus follow with cursor.. unfortunately I have to disable this on my work PC config.

It would be nice if there could be a rule you could configure for specific software you know doesn't behave properly with focus follow being enabled.

**Comment by lars-berger** [comment]
> This gave me an idea... I have issues with AutoDesk software but really enjoy focus follow with cursor.. unfortunately I have to disable this on my work PC config.
> 
> It would be nice if there could be a rule you could configure for specific software you know doesn't behave properly with focus follow being enabled.

@dillacorn Is it because AutoDesk has a lot of small popup windows? Could you share a screen recording of the behavior? 

@clownroyal420 Def agree it'd be a nice feature to have 👍 Do you have any preferences when it comes to how the API would look? An option would be to have something like `wm-toggle-cursor-jump` and `wm-toggle-focus-follows-cursor`, but there's probably also a use case for changing a particular option (e.g. `monitor_focus` -> `window_focus` as a trigger for cursor jump).

**Comment by dillacorn** [comment]
@lars-berger Yes.. (sorry for the late reply)

I'm having an inconsistent experience with Civil 3D. Some popup windows behave fine, but others require me to navigate with arrow keys unless I set certain flags in my config.

- `focus_follows_cursor: false`  
  *This must be disabled when working with Civil 3D.*

- `initial_state: "floating"`  
  *This seems to resolve most of the issues, though I dislike having to manually tile windows.*

Here's the relevant section from my config:

```yaml
- commands: ["ignore"]
  match:
    # Ignore Windows Input Experience (Civil 3D popups)
    - window_process: { equals: "TextInputHost" }  # Sometimes appears instead
    - window_process: { equals: "Windows Input Experience" }

    # Attempt to ignore acad software
    - window_process: { equals: "acad" }
      window_title: { regex: "Select|Properties|Layer|Plot|Hatch|^$" }
    - window_class: { regex: "Afx:.*|Autodesk.*Dialog|Adsk.*" }
    - window_process: { equals: "ADPClientService|AdskAccessUIHost|AdskAccessCore|AdSSO|AdskIdentityManager" }
```

To be honest, Civil 3D is quite outdated under the hood, and this is such a niche issue for me that I don't think it's worth spending much time on unless more users report similar problems (which I doubt will happen).

Config reference:  
https://github.com/dillacorn/win-glaze-dots/blob/main/UserProfile/.glzr/glazewm/custom_work_config.yaml

**Comment by alsaghir** [comment]
I was hoping for a delay config for focus_follows_cursor but a hold-down a key for escaping that option is another solution. very annoying issue for try based temp window apps (like some VPN apps) really.

**Comment by dillacorn** [comment]
Coming back to this after using both Hyprland and GlazeWM more extensively, I think `cursor_jump` would benefit from being split into independent behaviors rather than a single `monitor_focus` / `window_focus` choice.

Hyprland handles this more granularly with options such as `no_warps`, `persistent_warps`, `warp_on_change_workspace`, and `warp_on_monitor_change`. My Awtarchy config, for example, allows normal focus warping while explicitly disabling workspace-change warping:

```lua
cursor = {
    no_warps = false,
    persistent_warps = false,
    warp_on_change_workspace = 0,
}
```

GlazeWM could expose something similarly composable, for example:

```yaml
cursor_jump:
  enabled: true
  window_focus: true
  workspace_focus: false
  monitor_focus: true
```

That would allow directional keyboard focus to move the cursor to the newly focused window, same-monitor workspace changes or bar clicks to leave the cursor alone, and cross-monitor focus changes to bring the cursor with them.

Right now `monitor_focus` feels too limited while `window_focus` is too aggressive. Separating those cases would make cursor behavior much more predictable and configurable.
