### ISSUE TITLE
[Bug] GlazeWM breaks wslg

### ISSUE THREAD

**Issue by michidk** [glzr-io/glazewm#977]
### Describe the bug

Whenever glazewm is running and not in pause mode, all wslg windows (e.g. launching `xeyes` from wsl) will move (as intended, though with wrong spacing) but also freeze completely.

Might be releated to https://github.com/glzr-io/glazewm/issues/418, https://github.com/glzr-io/glazewm/issues/44

### Reproduction

Launch xeyes using wsl

### Stack trace or error logs (if applicable)

```shell

```

### Version number

v3.8.1

**Comment by nickscer** [comment]
I encountered the same issue, GUI applications work as intended when GlazeWM is paused tho.

**Comment by questamor** [comment]
As a temporary solution, you may configure msrdc as an ignored process, allowing wslg windows to be ignored by GlazeWM and preventing them from freezing.
```yaml
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'msrdc' }
```
