### ISSUE TITLE
[Bug] New window opens on the second screen instead of the focused workspace in the first screen

### ISSUE THREAD

**Issue by vitreo12** [glzr-io/glazewm#997]
### Describe the bug

I am encountering a bug where a new window is opened on the second monitor (where there's a workspace with a window open) instead of the focused workspace on the primary monitor.

https://github.com/user-attachments/assets/b86b1bef-f899-442b-a0a1-558003729cc1

### Stack trace or error logs (if applicable)

```shell

```

### Version number

3.8.1

**Comment by HolbyFPV** [comment]
Can you launching using the windows start menu instead?  I suspect PowerToys is to blame.  We have a similar workaround in place for Flow launcher.  A `force_manage` command targeting PowerToys should fix your issue once it's added.
https://github.com/glzr-io/glazewm/blob/151136657bff35800d70a2337c98ebe023532aca/packages/wm-platform/src/native_window.rs#L217

**Comment by vitreo12** [comment]
The launcher shown in the video is actually Flow launcher, not PowerToys, so I'm not sure that's the root cause. Same behavior happens if launching using the start menu.

**Comment by HolbyFPV** [comment]
This bug was common with launchers but never with the windows start menu.  I'm not sure what the root cause could be.  Do you do any customization of windows, run any programs to change your desktop experience other than GWM/Flow, or anything else that makes your system unique? My guess is there is an incompatibility somewhere.  

Other than that, some more detail on the behavior would be helpful.  Do programs consistently launch to the main window?  Is there any pattern or is it random?  Sometimes having a window open on one but not the other can make a difference, along with having no windows initially open.

**Comment by vitreo12** [comment]
I think my system is pretty vanilla, the only two programs I am using are Flow and GlazeWM.

It's probably worth noting that this behavior only happens if there already is another window open on the other monitor

**Comment by jtubbenhauer** [comment]
Just adding to this that I've been experiencing the same behaviour using PowerToys. Good to know that the Start menu is a workaround until a fix is released.

**Comment by ezswan** [comment]
I'm experiencing the same issue using a combination of Flow Launcher, GlazeWM, and Zebar.

I initially switched from the new PowerToys Command Palette because I couldn't get its window to be properly ignored—it would always appear in a tiled layout. When I set it to "ignored," any application launched through it was also ignored, which obviously isn’t ideal.

Now with Flow Launcher, the launcher itself is correctly ignored, and apps launched from it open as tiled windows, which is great. However, they open on the wrong workspace.

Really hoping for a solution here—Flow Launcher is a great tool, and I'd love to keep using it smoothly with this setup.

**Comment by crsanti** [comment]
I'm experiencing the same issue (GlazeWM, FlowLauncher, YASB Reborn). I tried with PowerToy launchers before and got same behavior. From my perspective I noticed when the launcher is closed (even if you open it and close it with `Esc`) the workspace on the non empty monitor is focused.

**Comment by Ma-Shell** [comment]
I also found this issue with PowerToys and FlowLauncher. This only happens if my target monitor is empty and the other monitor has at least one window on it.
Here is what seems to be happening:

When opening the launcher on the target monitor, the launcher becomes the focused window. After choosing an app, the launcher window disappears, which triggers Windows to automatically focus the next available window, which is the one from my other monitor. So once the other app actually opens its window, the active monitor is the one with the existing window.

I can also confirm this behavior by opening Flow Launcher on my empty monitor and then cancelling it (pressing ESC). Now the window on my other monitor is focused and not the empty workspace as before opening the launcher.

This is the log when cancelling Flow Launcher (with 1248716 being the window on my secondary monitor):
```
2025-10-03T19:17:42.206955Z  INFO glazewm::events::handle_window_focused: Window manually focused: Window(hwnd=1248716, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Docume...)
2025-10-03T19:17:42.207199Z  INFO glazewm::commands::general::platform_sync: Updating window z-order: Window(hwnd=1248716, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Docume...)
```

This is the log from opening Chrome:
```
2025-10-03T19:20:13.186152Z  INFO glazewm::events::handle_window_focused: Window manually focused: Window(hwnd=1248716, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Docume...)
2025-10-03T19:20:13.186409Z  INFO glazewm::commands::general::platform_sync: Updating window z-order: Window(hwnd=1248716, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Docume...)
2025-10-03T19:20:13.188165Z  INFO glazewm: Received IPC message: "query monitors"
2025-10-03T19:20:13.188920Z  INFO glazewm: Received IPC message: "query monitors"
2025-10-03T19:20:13.189786Z  INFO glazewm: Received IPC message: "query windows"
2025-10-03T19:20:13.190458Z  INFO glazewm: Received IPC message: "query windows"
2025-10-03T19:20:13.190994Z  INFO glazewm: Received IPC message: "query tiling-direction"
2025-10-03T19:20:13.191535Z  INFO glazewm: Received IPC message: "query tiling-direction"
2025-10-03T19:20:13.207688Z  INFO glazewm::events::handle_window_title_changed: Window title changed: Window(hwnd=1248716, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Docume...)
2025-10-03T19:20:13.244314Z  INFO glazewm::commands::window::manage_window: New window managed: Window(hwnd=4459708, process=chrome, class=Chrome_WidgetWin_1, title=Neuer Tab - Googl...)
2025-10-03T19:20:13.244592Z  INFO glazewm::commands::general::platform_sync: Setting focus to window: Window(hwnd=4459708, process=chrome, class=Chrome_WidgetWin_1, title=Neuer Tab - Googl...)
2025-10-03T19:20:13.247802Z  INFO glazewm::commands::general::platform_sync: Updating window position: Window(hwnd=1248716, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Docume...)
2025-10-03T19:20:13.254527Z  INFO glazewm::commands::general::platform_sync: Updating window position: Window(hwnd=4459708, process=chrome, class=Chrome_WidgetWin_1, title=Neuer Tab - Googl...)
found window: Neuer Tab - Google Chrome 4459708
2025-10-03T19:20:13.258816Z  INFO glazewm_watcher: Watcher added handle: 4459708.
handle_window_focused: Neuer Tab - Google Chrome 4459708 -> Neuer Tab - Google Chrome 4459708
2025-10-03T19:20:13.260592Z  INFO glazewm::commands::general::platform_sync: Updating window z-order: Window(hwnd=1248716, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Docume...)
2025-10-03T19:20:13.260939Z  INFO glazewm::commands::general::platform_sync: Updating window z-order: Window(hwnd=4459708, process=chrome, class=Chrome_WidgetWin_1, title=Neuer Tab - Googl...)
```

Inerestingly though, this does not happen, if I manually close the last window of the workspace.
Here is what the log says if I close the last terminal on a workspace:
```
2025-10-03T19:19:04.704478Z  INFO glazewm::events::handle_window_hidden: Window hidden: Window(hwnd=6032190, process=wezterm-gui, class=org.wezfurlong.wezterm, title=MINGW64:/c/Users/...)
2025-10-03T19:19:04.704706Z  INFO glazewm::commands::general::platform_sync: Setting focus to the desktop window.
2025-10-03T19:19:04.707994Z  INFO glazewm_watcher: Watcher removed handle: 6032190.
```

**Comment by Ma-Shell** [comment]
After some further investigation I found that the issue boils down to the launcher being unmanaged. 

> Can you try launching using the windows start menu instead? I suspect PowerToys is to blame. We have a similar workaround in place for Flow launcher. A `force_manage` command targeting PowerToys should fix your issue once it's added.
> 
> [glazewm/packages/wm-platform/src/native_window.rs](https://github.com/glzr-io/glazewm/blob/151136657bff35800d70a2337c98ebe023532aca/packages/wm-platform/src/native_window.rs#L217)
> 
> Line 217 in [1511366](/glzr-io/glazewm/commit/151136657bff35800d70a2337c98ebe023532aca)
> 
>  if process_name == "Flow.Launcher" && title == "Flow.Launcher" {

For me the process_name is just "Flow". Once I changed it and recompiled, it worked for me:
```rust
    if process_name == "Flow" && title == "Flow.Launcher" {
      return Ok(true);
    }
```

I also added this to my config.yaml:
```
window_rules:
  - commands: ['set-floating']
    match:
      - window_process: { regex: 'Flow(\\.Launcher\\.exe)?' }
```

**Comment by ezswan** [comment]
> I also found this issue with PowerToys and FlowLauncher. This only happens if my target monitor is empty and the other monitor has at least one window on it. Here is what seems to be happening:
> 
> When opening the launcher on the target monitor, the launcher becomes the focused window. After choosing an app, the launcher window disappears, which triggers Windows to automatically focus the next available window, which is the one from my other monitor. So once the other app actually opens its window, the active monitor is the one with the existing window.
> 
> I can also confirm this behavior by opening Flow Launcher on my empty monitor and then cancelling it (pressing ESC). Now the window on my other monitor is focused and not the empty workspace as before opening the launcher.

This is 100 percent the issue, and I don’t know how to fix it. I’m using the PowerToys Command Palette now instead of Flow Launcher, but the same problem happens. When you open a program through a launcher, if the current workspace on Monitor 1 doesn’t already have another window open, GlazeWM will refocus to the workspace on the second monitor because that one does have a window. It basically pulls focus over there while the new program is still loading, which causes the app you selected to launch on the wrong monitor instead of the one you intended.

**Comment by CocoJamb0O** [comment]
That's terrible, but as an alternative, I suggest you use a rule to launch all programs on the main monitor and configure the rest to launch on the other monitors. I use this approach in combination with the “Workspaces” feature from PowerToys; it seems much more convenient than relying on all new programs to open on Monitor 0.

Look at the code - that’s my primary monitor. This approach ensures that the Windows Start menu works correctly:
```yaml
window_rules:
# move to workspaces 
 # Move to workspace 2
  - commands: ['move --workspace 1']
    match:
      - window_process: { not_regex: 'StartMenuExperienceHost|ShellExperienceHost|SearchHost|explorer|SystemSettings|ApplicationFrameHost' }
```

<details>
  <summary>My configuration:</summary>

  ```yaml
  general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  #startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'window_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': (Windows-only) Recommended option for Windows.
  # - 'hide': (Windows-only) Legacy option for Windows. Has stability issues with some apps.
  # - 'place_in_corner': Artifically hides the window by placing it in the corner of the
  #   monitor. On macOS, this is always used instead of cloak/hide.
  hide_method: 'cloak'

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: false

  # Gap between adjacent windows.
  inner_gap: '-1px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '-1px'
    right: '-1px'
    bottom: '-1px'
    left: '-1px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: false
      color: '#8dbcff'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: true
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: '95%'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: false
      opacity: '0%'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: true

      # Whether to show fullscreen windows as always on top.
      shown_on_top: true

workspaces:
  - name: '0'
    bind_to_monitor: 0
    keep_alive: true
  - name: '1'
    bind_to_monitor: 1
    keep_alive: true
  - name: '2'
    bind_to_monitor: 2
    keep_alive: true

window_rules:
# move to workspaces 
 # Move to workspace 2
  - commands: ['move --workspace 1']
    match:
      - window_process: { not_regex: 'StartMenuExperienceHost|ShellExperienceHost|SearchHost|explorer|SystemSettings|ApplicationFrameHost' }

 # Move to workspace 1
  - commands: ['move --workspace 0']
    match:
      - window_process: { regex: 'KeePassXC|Discord|Telegram' }

  # Move to workspace 3
  - commands: ['move --workspace 2']
    match:
      - window_process: { regex: 'msedge|brave|chrome|vivaldi|firefox' }
      # Audio
      - window_process: { regex: 'SteelSeriesGGClient|Soundpad' }

  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'steamwebhelper' }
        window_class: { regex: 'SDL_app' }
      - window_title: { equals: 'Command Palette' }
        window_class: { equals: 'WinUIDesktopWin32WindowClass' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }

      # Games
      - window_process: { equals: 'cs2' }
      - window_process: { equals: 'aces' }
  ```
  
</details>
